"""Especificação das criaturas da POA 1987 — fonte única do gerador.

Convenções (documentadas no rascunho do bestiário):
  · categoria do tesouro segue o tier: T0/T1 Adepto, T2 Experiente, T3 Mestre
  · Artilharia é sempre Fator positivo (Lênica é química do sangue) e o Fator
    vira a Sintonia: O+ Fogo · A+ Terra · B+ Vento · AB+ Água
  · quem tem arma a distância leva backup corpo-a-corpo (exceto sem-mão)
  · pólvora (Bacamarte/Pistola Arcanônica) só com contrato estatal
"""

# Tipagem → nota de `categoria: Sintonia`. Os Fatores POSITIVOS são os Traços
# Elementais do sistema (o reskin já os exibe como "Fator X+"); os NEGATIVOS e
# as duas trônicas são notas próprias da POA (Sintonia/Tipagens).
SINTONIA = {
    "O+": "[[Traço Elemental do Fogo]]",
    "A+": "[[Traço Elemental da Terra]]",
    "B+": "[[Traço Elemental do Vento]]",
    "AB+": "[[Traço Elemental da Água]]",
    "O−": "[[Fator O Negativo]]",
    "A−": "[[Fator A Negativo]]",
    "B−": "[[Fator B Negativo]]",
    "AB−": "[[Fator AB Negativo]]",
    "Positrônico": "[[Fator Positrônico]]",
    "Negatrônico": "[[Fator Negatrônico]]",
}
CAT_POR_TIER = {0: "Adepto", 1: "Adepto", 2: "Experiente", 3: "Mestre"}

# ── magias por linha e elemento (nomes canônicos do Sistema) ──────────────────
LENICA = {
    "Fogo": ["Raio Flamejante", "Estouro", "Coluna de Fogo", "Cone de Fogo", "Combustão",
             "Bola de Fogo", "Manto Incendiário"],
    "Terra": ["Pulso Sísmico", "Escudo Rochoso", "Barreira de Pedra", "Onda de Choque",
              "Tremor", "Rocha Empaladora", "Pele de Pedra"],
    "Vento": ["Corte de Vento", "Vento Mensageiro", "Lufada de Vento", "Vento Guardião",
              "Passos do Vento", "Pressurização Repentina", "Propulsão Explosiva"],
    "Água": ["Esfera d'Água", "Frio Instantâneo", "Atadura d'Água", "Rajada d'água",
             "Caminho de Gelo", "Hidrovitalizar", "Onda d'água", "Cristalização Gélida"],
}
POSITRONICA = ["Guiar", "Proteger", "Avivar", "Celeridade", "Empoderar", "Encantar Arma",
               "Melhorar Habilidade", "Passos Rápidos", "Aceleração", "Heroísmo",
               "Regeneração", "Aceleração em Massa"]
NEGATRONICA = ["Aturdir", "Choque Mental", "Drenar", "Enfraquecer", "Entorpecer",
               "Aterrorizar", "Ofuscação", "Míssil Mágico", "Lentidão", "Confusão",
               "Distorção Sensorial", "Sifão Vital", "Condenar", "Lentidão em Massa"]


def magias(linha: str, tier: int, elemento: str | None = None) -> list[str]:
    """Quantidade por tier (espelha o Goblin Piromante, Artilharia T1 = 4)."""
    n = {0: 3, 1: 4, 2: 5, 3: 6}[tier]
    if linha == "Anima":
        return LENICA[elemento][:n]
    return (POSITRONICA if linha == "Arcana Branca" else NEGATRONICA)[:n]


def A(nome, prop=None, tier=None):
    """Arma: nome canônico + propriedade (módulo/premium) com a categoria do tier."""
    a = {"nome": nome}
    if prop:
        a["propriedade"] = prop
        a["categoria"] = CAT_POR_TIER[tier]
    return a


def INV(armadura=None, escudo=None, tesouros=(), consumiveis=(), ouro=0, tier=0):
    inv = {"tesouros": list(tesouros), "consumiveis": list(consumiveis), "ouro": ouro}
    if armadura:
        nome, prop = (armadura if isinstance(armadura, tuple) else (armadura, None))
        inv["armadura"] = {"nome": nome, "categoria": CAT_POR_TIER[tier] if prop else "",
                           "propriedade": prop}
    if escudo:
        nome, prop = (escudo if isinstance(escudo, tuple) else (escudo, None))
        inv["escudo"] = {"nome": nome, "categoria": CAT_POR_TIER[tier] if prop else "",
                         "propriedade": prop,
                         "dano": 4 if nome == "Escudo" else 2,
                         "dureza": 5 if nome == "Escudo" else 3}
    return inv


def C(nome, tier, papel, principal, F, Ag, I, P, pericias, armas, inventario, *,
      mod=None, org="", bairros=(), habilidades=(), tipagem="O−", linha_magia=None,
      elemento=None, raca=None, tamanho="Médio", descricao="", aliases=()):
    spec = {
        "nome": nome, "tier": tier, "papel": papel, "mod": mod, "principal": principal,
        "atributos": {"FOR": F, "AGI": Ag, "INT": I, "PRE": P},
        "pericias": pericias, "armas": armas, "inventario": inventario,
        "habilidades": list(habilidades), "org": org, "bairros": list(bairros),
        "tipagem": tipagem, "descricao": descricao, "aliases": list(aliases),
        "tamanho": tamanho,
    }
    if raca:
        spec["raca"] = raca
    if linha_magia:
        spec["linha_magia"] = linha_magia
        spec["magias"] = magias(linha_magia, tier, elemento)
    # Encantador e Supressor não operam por sangue: operam por IMPLANTE — a
    # tipagem deles é a linha trônica que rodam, não o Fator do RG.
    if papel == "Encantador":
        tipagem = "Positrônico"
    elif papel == "Supressor":
        tipagem = "Negatrônico"
    if tipagem in SINTONIA:
        spec["sintonia"] = SINTONIA[tipagem]
    spec["tipagem"] = tipagem
    return spec


B = "[[Brigada Militar Metropolitana]]"
INCOMUM = "[[Incomum|Incomum]]"

CRIATURAS = [
    # ─────────────────────────── Estado ───────────────────────────
    C("Brigadiano de Esquina", 0, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Guerra", "A"), ("Sociedades", "A")],
      [A("Porrete")], INV(tier=0), org=B, bairros=["[[Porto Alegre]]"],
      descricao="A dupla de farda que para o herói na calçada e pede o laudo. Sozinho não resolve nada; o problema é o rádio no ombro."),
    C("Cão de Brigada", 0, "Batedor", "AGI", 2, 3, 0, 1,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Atletismo", "A")],
      [A("Presas de Lobo")], INV(tier=0), org=B, bairros=["[[Porto Alegre]]"],
      habilidades=["Restringir Movimento", "Farejar Dose"], tipagem="—",
      raca=INCOMUM, descricao="Fareja dose e sangue. Prende o herói no lugar até a farda chegar."),
    C("Brigadiano Atirador", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Furtividade", "A"), ("Guerra", "A"), ("Atletismo", "A"), ("Lênicos", "A"), ("Sociedades", "A")],
      [A("Besta de Mão"), A("Adaga")],
      INV(armadura="Armadura Leve", consumiveis=["Poção de Cura", "Poção de Cura"], ouro=2, tier=1),
      org=B, bairros=["[[Porto Alegre]]"], habilidades=["Tiro de Cobertura"],
      tipagem="B+", linha_magia="Anima", elemento="Vento",
      descricao="O bico de brigadiano: sem farda, com dardo selênico e um nome que ninguém anota."),
    C("Cabo de Choque", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Guerra", "A"), ("Acrobacia", "A"), ("Sociedades", "A")],
      [A("Porrete", "Imbuição Sísmica", 1), A("Escudo")],
      INV(armadura="Armadura Leve", escudo="Escudo", consumiveis=["Poção da Coragem"], ouro=1, tier=1),
      mod="Competente", org=B, bairros=["[[Centro Histórico]]", "[[Bom Fim]]", "[[Cidade Baixa]]"],
      habilidades=["Restringir Movimento", "Parede de Escudo"], tipagem="A−",
      descricao="Formação de escudo da Operação Silêncio. Empurra, prensa na parede e não deixa passar."),
    C("Atirador de Torre", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Guerra", "A"), ("Furtividade", "A"), ("Atletismo", "A"), ("Lênicos", "A"), ("Sobrevivência", "A")],
      [A("Besta Leve"), A("Espada Curta")],
      INV(tesouros=["Amplificador Audiovisual"], consumiveis=["Poção de Cura"], ouro=2, tier=1),
      org=B, bairros=["[[Restinga]]", "[[Zona Deserta]]", "[[Quarto Distrito]]"],
      habilidades=["Tiro de Cobertura"], tipagem="O+", linha_magia="Anima", elemento="Fogo",
      descricao="Fica na guarita e queima a rua de longe. Some quando o herói chega perto."),
    C("Piloto de Anfíbio", 1, "Batedor", "AGI", 2, 3, 1, 0,
      [("Atletismo", "A"), ("Acrobacia", "A"), ("Sobrevivência", "A"), ("Guerra", "A"), ("Malandragem", "A")],
      [A("Porrete"), A("Lança")],
      INV(armadura="Armadura Leve", consumiveis=["Poção da Velocidade"], ouro=1, tier=1),
      org=B, bairros=["[[Cidade Baixa]]", "[[Praia de Belas]]", "[[Lago Guaíba]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="B−",
      descricao="Chega pela água na tocaia da Cidade Baixa. Dirige, atropela e recua."),
    C("Sargento de Pelotão", 2, "Líder", "PRE", 2, 0, 1, 3,
      [("Guerra", "E"), ("Intimidação", "E"), ("Sociedades", "A"), ("Atletismo", "A"), ("Diplomacia", "A")],
      [A("Espada Curta", "Arma Obra-prima", 2), A("Porrete")],
      INV(armadura="Armadura Leve", tesouros=["Brasão Tático"],
          consumiveis=["Poção de Cura", "Poção de Cura"], ouro=8, tier=2),
      mod="Competente", org=B, bairros=["[[Porto Alegre]]"],
      habilidades=["Ordem de Ataque", "Não Recuem"], tipagem="A−",
      descricao="Não é o mais forte: é o que faz os outros oito valerem por dezesseis. Mata-se ele primeiro."),
    C("Franco-Atirador da Brigada", 2, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Furtividade", "E"), ("Guerra", "E"), ("Atletismo", "A"), ("Lênicos", "A"), ("Acrobacia", "A")],
      [A("Besta", "Arma Obra-prima", 2), A("Adaga")],
      INV(tesouros=["Capa Discreta"], consumiveis=["Poção da Velocidade"] * 3, ouro=6, tier=2),
      mod="Competente", org=B, bairros=["[[Centro Histórico]]", "[[Moinhos de Vento]]", "[[Petrópolis]]"],
      habilidades=["Tiro de Cobertura", "Alvo de Assassinato"], tipagem="B+",
      linha_magia="Anima", elemento="Vento",
      descricao="Dardo selênico do telhado. Escolhe um alvo por rodada e pune quem se expõe."),
    C("Exoesqueleto do BOPE", 2, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "E"), ("Intimidação", "E"), ("Guerra", "A"), ("Acrobacia", "A")],
      [A("Malho", "Imbuição Mineral", 2)],
      INV(armadura="Armadura Pesada", tesouros=["Pulseira da Potência"],
          consumiveis=["Poção da Coragem", "Poção da Coragem"], ouro=10, tier=2),
      mod="Elite", org=B, bairros=["[[Petrópolis]]", "[[Passo D'Areia]]", "[[Nova Sarandi]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="A−",
      descricao='O "bope corporativo": casco Tramontina e rádio Gradiente. O muro que entra na frente.'),
    C("Pelotão de Guarnição", 3, "Soldado", "FOR", 3, 1, 1, 1,
      [("Guerra", "M"), ("Atletismo", "M"), ("Intimidação", "E"), ("Sociedades", "E"), ("Medicina", "A")],
      [A("Bacamarte Arcanônico", "Arma Obra-prima", 3), A("Espada Curta")],
      INV(armadura="Armadura Pesada", escudo="Escudo",
          consumiveis=["Poção de Cura", "Poção de Cura"], ouro=20, tier=3),
      mod="Elite", org="[[Governo Militar Brasileiro]]", bairros=["[[Costa e Silva]]", "[[Zona Deserta]]"],
      habilidades=["Restringir Movimento", "Parede de Escudo"], tipagem="O−",
      descricao="Tropa de quartel, com pólvora legal. Não negocia e não corre."),
    C("Oficial de Operações", 3, "Líder", "PRE", 1, 0, 2, 3,
      [("Guerra", "M"), ("Diplomacia", "M"), ("Sociedades", "E"), ("Intimidação", "E"),
       ("Enganação", "A"), ("Malandragem", "A")],
      [A("Pistola Arcanônica", "Arma Obra-prima", 3), A("Espada Curta")],
      INV(armadura=("Armadura Pesada", "Armadura Obra-prima"), tesouros=["Anel Mensageiro"],
          consumiveis=["Poção de Cura", "Poção de Cura"], ouro=40, tier=3),
      mod="Solo", org="[[Governo Militar Brasileiro]]", bairros=["[[Costa e Silva]]", "[[Centro Histórico]]"],
      habilidades=["Ordem de Ataque", "Fechar Formação", "Não Recuem"], tipagem="A−",
      descricao="Coordena toque de recolher e apoio aéreo: a cena inteira é ele."),
    C("Coronel Luciana Prado", 3, "Líder", "PRE", 1, 0, 2, 3,
      [("Guerra", "M"), ("Intimidação", "M"), ("Diplomacia", "E"), ("Sociedades", "E"),
       ("Enganação", "A"), ("Malandragem", "A")],
      [A("Pistola Arcanônica", "Imbuição de Ferro Frio", 3), A("Espada Curta")],
      INV(armadura=("Armadura Pesada", "Armadura Obra-prima"), tesouros=["Brasão Tático"],
          consumiveis=["Poção de Cura"] * 3, ouro=50, tier=3),
      mod="Solo", org=B, bairros=["[[Centro Histórico]]", "[[Bom Fim]]"],
      habilidades=["Ordem de Ataque", "Não Recuem", "Alvo de Assassinato"], tipagem="AB−",
      aliases=["Coronel Prado"],
      descricao="Quem assina a Operação Silêncio. A Pessoa da vault com ficha de combate."),
]

CRIATURAS += [
    # ─────────────────────── Megacorporações ───────────────────────
    C("Segurança de Crachá", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sociedades", "A"), ("Guerra", "A"), ("Diplomacia", "A")],
      [A("Porrete")], INV(armadura="Armadura Leve", ouro=2, tier=1),
      org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]", "[[Ipanema]]", "[[Centro Histórico]]"],
      tipagem="A−", descricao="Porteiro armado de prédio corporativo. Barra quem não tem crachá e chama a Brigada."),
    C("Drone de Vigilância", 1, "Batedor", "AGI", 0, 3, 2, 1,
      [("Furtividade", "A"), ("Acrobacia", "A"), ("Trônicos", "A"), ("Atletismo", "A"), ("Sociedades", "A"), ("Guerra", "A")],
      [A("Besta de Mão")], INV(tesouros=["Amplificador Audiovisual"], tier=1),
      org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]", "[[Ipanema]]", "[[Jardim Botânico]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="—", raca=INCOMUM, tamanho="Pequeno",
      descricao="Vê, marca e chama reforço. Matar é fácil; matar antes de ele transmitir é que é o problema."),
    C("Operador Trônico", 2, "Encantador", "INT", 0, 1, 3, 2,
      [("Trônicos", "E"), ("Sociedades", "E"), ("Enganação", "A"), ("Malandragem", "A"),
       ("Medicina", "A"), ("Diplomacia", "A"), ("Acrobacia", "A")],
      [A("Adaga")], INV(tesouros=["Luva do Arcanista"], consumiveis=["Poção da Coragem"] * 2, ouro=12, tier=2),
      mod="Competente", org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]", "[[Centro Histórico]]"],
      habilidades=["Dose no Braço"], tipagem="AB−", linha_magia="Arcana Branca",
      descricao="Roda rotina nos próprios colegas: o capanga ao lado dele fica melhor do que devia."),
    C("Escolta de Diretoria", 2, "Assassino", "AGI", 2, 3, 0, 1,
      [("Furtividade", "E"), ("Acrobacia", "E"), ("Atletismo", "A"), ("Malandragem", "A")],
      [A("Pistola Arcanônica", "Arma Obra-prima", 2), A("Punhal")],
      INV(armadura="Armadura Leve", tesouros=["Anel Canário"],
          consumiveis=["Poção de Cura"] * 2, ouro=15, tier=2),
      mod="Competente", org="[[Gradiente]]", bairros=["[[Ipanema]]", "[[Moinhos de Vento]]"],
      habilidades=["Alvo de Assassinato"], tipagem="O−",
      descricao="Terno, contrato estatal e porte legal. Escolhe UM da mesa e vai só nele."),
    C("Auditor de Campo", 3, "Supressor", "INT", 0, 1, 3, 2,
      [("Trônicos", "M"), ("Sociedades", "M"), ("Enganação", "E"), ("Malandragem", "E"),
       ("Medicina", "A"), ("Diplomacia", "A"), ("Furtividade", "A")],
      [A("Adaga de Duelo", "Imbuição de Ferro Frio", 3)],
      INV(armadura="Armadura Leve", tesouros=["Luvas do Ladrão"],
          consumiveis=["Poção da Velocidade"] * 2, ouro=35, tier=3),
      mod="Elite", org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]", "[[Petrópolis]]", "[[Nova Sarandi]]"],
      habilidades=["Restringir Movimento", "Queimar a Rota"], tipagem="A−", linha_magia="Arcana Negra",
      descricao="Quando a firma vira inimiga: corta rota, tranca porta e desliga implante de quem tem registro."),
    C("Sistemista da Gradiente", 3, "Encantador", "INT", 0, 1, 3, 2,
      [("Trônicos", "M"), ("Sociedades", "M"), ("Enganação", "E"), ("Diplomacia", "E"),
       ("Malandragem", "A"), ("Medicina", "A"), ("Acrobacia", "A")],
      [A("Punhal", "Arma Obra-prima", 3)],
      INV(tesouros=["Luva do Arcanista"], consumiveis=["Poção de Cura"] * 3, ouro=60, tier=3),
      mod="Solo", org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]"],
      habilidades=["Dose no Braço", "Fechar Formação"], tipagem="AB−", linha_magia="Arcana Branca",
      descricao="O topo da escada trônica. Não luta: usa a cidade — semáforo, elevador, rádio — como arma."),
    C("Segurança de Portaria", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Guerra", "A"), ("Intimidação", "A"), ("Sociedades", "A"), ("Sobrevivência", "A")],
      [A("Espada Curta", "Arma Obra-prima", 1)],
      INV(armadura="Armadura Leve", ouro=2, tier=1),
      mod="Competente", org="[[Tramontina]]", bairros=["[[Petrópolis]]", "[[Nova Sarandi]]"],
      tipagem="O−", descricao="A firma que fabrica a lâmina também a carrega. Uniforme limpo, faca com número de série."),
    C("Protótipo de Exoesqueleto", 2, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "E"), ("Intimidação", "E"), ("Guerra", "A"), ("Acrobacia", "A")],
      [A("Martelo de Guerra", "Imbuição Sísmica", 2)],
      INV(armadura="Armadura Pesada", tesouros=["Pulseira da Potência"], tier=2),
      mod="Elite", org="[[Tramontina]]", bairros=["[[Petrópolis]]"],
      habilidades=["Vigor Bruto", "Casco"], tipagem="—", raca=INCOMUM, tamanho="Grande",
      descricao="Máquina de teste solta no galpão do Instituto Técnico. Não sabe que parou de ser um exercício."),
    C("Modelo Militar", 3, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "M"), ("Intimidação", "M"), ("Guerra", "E"), ("Acrobacia", "E")],
      [A("Montante", "Imbuição Explosiva", 3)],
      INV(armadura=("Armadura Pesada", "Armadura Obra-prima"), tesouros=["Pulseira da Potência"], tier=3),
      mod="Solo", org="[[Tramontina]]", bairros=["[[Zona Deserta]]", "[[Costa e Silva]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Grande", descricao="A encomenda do regime. O chefão de metal."),
    C("Fiscal de Patente", 1, "Supressor", "INT", 0, 1, 3, 2,
      [("Trônicos", "A"), ("Medicina", "A"), ("Sociedades", "A"), ("Enganação", "A"),
       ("Malandragem", "A"), ("Diplomacia", "A"), ("Furtividade", "A")],
      [A("Porrete")], INV(tesouros=["Luvas Purificadas"], consumiveis=["Poção da Nutrição"] * 2, ouro=3, tier=1),
      org="[[Panvel]]", bairros=["[[Jardim Itu]]", "[[Bom Fim]]", "[[Restinga]]"],
      habilidades=["Queimar a Rota"], tipagem="B−", linha_magia="Arcana Negra",
      descricao="Fecha bancada clandestina. Não bate: derruba o químico e leva a dose."),
    C("Químico de Campo", 2, "Artilharia", "PRE", 0, 1, 2, 3,
      [("Lênicos", "E"), ("Medicina", "E"), ("Sobrevivência", "A"), ("Malandragem", "A"),
       ("Furtividade", "A"), ("Guerra", "A")],
      [A("Besta de Mão"), A("Adaga")],
      INV(tesouros=["Bracelete Elemental"], consumiveis=["Poção da Nutrição"] * 2, ouro=10, tier=2),
      mod="Competente", org="[[Panvel]]", bairros=["[[Jardim Itu]]", "[[Delta Radioativo]]"],
      habilidades=["Tiro de Cobertura"], tipagem="AB+", linha_magia="Anima", elemento="Água",
      descricao="Joga química de área. O dano é o menor problema: o que fica no chão continua queimando."),
    C("Escolta de Comboio", 2, "Batedor", "AGI", 2, 3, 1, 0,
      [("Atletismo", "E"), ("Acrobacia", "E"), ("Guerra", "A"), ("Sobrevivência", "A"), ("Malandragem", "A")],
      [A("Alabarda", "Arma Obra-prima", 2), A("Espada Curva")],
      INV(armadura="Armadura Leve", tesouros=["Cinto dos Ermos"],
          consumiveis=["Poção da Velocidade"], ouro=8, tier=2),
      mod="Competente", org="[[Zaffari]]", bairros=["[[Praia de Belas]]", "[[Nova Sarandi]]", "[[Lago Guaíba]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="O−",
      descricao="Protege carga em movimento. A luta dele é sempre em cima de algo que anda."),
]

CRIATURAS += [
    # ─────────────────────────── Facções ───────────────────────────
    C("Cobrador de Ponto", 0, "Soldado", "FOR", 3, 1, 1, 1,
      [("Intimidação", "A"), ("Sociedades", "A"), ("Malandragem", "A"), ("Atletismo", "A")],
      [A("Manopla")], INV(tier=0), org="[[Aliança dos Fundadores]]", bairros=["[[Centro Histórico]]"],
      tipagem="A−", descricao="Passa na banca toda sexta. Educado até a terceira semana sem pagamento."),
    C("Velho da Família", 2, "Líder", "PRE", 1, 0, 2, 3,
      [("Sociedades", "E"), ("Diplomacia", "E"), ("Enganação", "A"), ("Intimidação", "A"),
       ("Malandragem", "A"), ("Medicina", "A")],
      [A("Punhal", "Arma Obra-prima", 2)],
      INV(tesouros=["Colar da Eloquência"], consumiveis=["Poção de Cura"], ouro=15, tier=2),
      mod="Competente", org="[[Aliança dos Fundadores]]", bairros=["[[Centro Histórico]]"],
      habilidades=["Ordem de Ataque", "Não Recuem"], tipagem="A−",
      descricao="Manda sem levantar a voz, do fundo do Mercado Público. Quem encosta nele encosta em três bairros."),
    C("Passador de Dose", 0, "Encantador", "INT", 0, 1, 3, 2,
      [("Medicina", "A"), ("Malandragem", "A"), ("Enganação", "A"), ("Trônicos", "A"),
       ("Sociedades", "A"), ("Diplomacia", "A")],
      [A("Adaga")], INV(consumiveis=["Poção de Cura", "Poção da Coragem"], tier=0),
      org="[[Cartéis de Selênicos]]", bairros=["[[Restinga]]", "[[Cidade Baixa]]", "[[Quarto Distrito]]"],
      habilidades=["Dose no Braço"], tipagem="B−", linha_magia="Arcana Branca",
      descricao="Não briga: injeta. O capanga ao lado dele levanta de novo."),
    C("Mula do Cartel", 0, "Batedor", "AGI", 1, 3, 0, 2,
      [("Furtividade", "A"), ("Acrobacia", "A"), ("Malandragem", "A")],
      [A("Adaga de Duelo")], INV(consumiveis=["Poção da Velocidade"] * 2, tier=0),
      org="[[Cartéis de Selênicos]]", bairros=["[[Delta Radioativo]]", "[[Cidade Baixa]]", "[[Restinga]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="O−",
      descricao="Corre com a carga na cintura. Luta só o suficiente pra sumir na esquina."),
    C("Braço Armado do Cartel", 2, "Soldado", "FOR", 3, 1, 1, 1,
      [("Intimidação", "E"), ("Atletismo", "E"), ("Guerra", "A"), ("Malandragem", "A"), ("Sobrevivência", "A")],
      [A("Espada Curva", "Arma Obra-prima", 2), A("Manopla")],
      INV(armadura="Armadura Leve", consumiveis=["Poção da Coragem"], ouro=12, tier=2),
      mod="Elite", org="[[Cartéis de Selênicos]]", bairros=["[[Jardim Itu]]", "[[Praia de Belas]]"],
      habilidades=["Restringir Movimento", "Casco"], tipagem="O−",
      descricao="A escolta da carga grande. Nenhuma vontade de conversar."),
    C("Barão do Cartel", 3, "Líder", "PRE", 1, 0, 2, 3,
      [("Sociedades", "M"), ("Intimidação", "M"), ("Enganação", "E"), ("Diplomacia", "E"),
       ("Malandragem", "A"), ("Medicina", "A")],
      [A("Pistola Arcanônica", "Arma Obra-prima", 3), A("Punhal")],
      INV(armadura="Armadura Leve", tesouros=["Colar da Eloquência"],
          consumiveis=["Poção de Cura"], ouro=60, tier=3),
      mod="Solo", org="[[Cartéis de Selênicos]]", bairros=["[[Jardim Itu]]", "[[Restinga]]"],
      habilidades=["Ordem de Ataque", "Não Recuem"], tipagem="AB−",
      descricao="O dono da rota. A garrucha dele é prova de que o Estado é sócio."),
    C("Barqueiro Armado", 0, "Batedor", "AGI", 2, 3, 0, 1,
      [("Atletismo", "A"), ("Sobrevivência", "A"), ("Malandragem", "A")],
      [A("Lança")], INV(tier=0), org="[[Aliança Livre das Palafitas]]",
      bairros=["[[Cidade Baixa]]", "[[Lago Guaíba]]"], habilidades=["Pelo Telhado"], tipagem="B−",
      descricao="Leva, cobra e às vezes entrega o passageiro. Luta em cima d'água, onde ele não cai e tu cai."),
    C("Atirador de Palafita", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Lênicos", "A"), ("Atletismo", "A"), ("Malandragem", "A")],
      [A("Besta Pesada"), A("Adaga")],
      INV(consumiveis=["Poção de Cura"], ouro=1, tier=1),
      org="[[Aliança Livre das Palafitas]]", bairros=["[[Cidade Baixa]]"],
      habilidades=["Tiro de Cobertura"], tipagem="AB+", linha_magia="Anima", elemento="Água",
      descricao="Atira de cima da tábua e recua pelo varal. A passarela é a defesa dele."),
    C("Catador Armado", 0, "Batedor", "AGI", 2, 3, 0, 1,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Malandragem", "A")],
      [A("Azagaia")], INV(tier=0), org="[[Sindicato dos Catadores]]",
      bairros=["[[Zona Deserta]]", "[[Restinga]]", "[[Centro Histórico]]"],
      habilidades=["Oportunista"], tipagem="O−",
      descricao="O olheiro do ferro-velho. Sabe qual pilha esconde o quê — e quem passou por ali."),
    C("Ferro-Velho", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sobrevivência", "A"), ("Guerra", "A")],
      [A("Malho", "Imbuição Mineral", 1)],
      INV(tesouros=["Pulseira da Potência"], ouro=1, tier=1),
      mod="Competente", org="[[Clã da Ferrugem]]", bairros=["[[Zona Deserta]]", "[[Restinga]]", "[[Petrópolis]]"],
      habilidades=["Vigor Bruto"], tipagem="A−",
      descricao="Prótese de sucata e marreta. Bate igual à máquina de onde tirou o braço."),
    C("Mestre de Sucata", 2, "Líder", "PRE", 1, 0, 2, 3,
      [("Sobrevivência", "E"), ("Sociedades", "E"), ("Intimidação", "A"), ("Malandragem", "A"),
       ("Medicina", "A"), ("Guerra", "A")],
      [A("Maça", "Imbuição Relampejante", 2), A("Azagaia")],
      INV(armadura="Armadura Leve", tesouros=["Cinto dos Ermos"],
          consumiveis=["Poção de Cura"], ouro=10, tier=2),
      mod="Competente", org="[[Clã da Ferrugem]]", bairros=["[[Zona Deserta]]", "[[Restinga]]"],
      habilidades=["Ordem de Ataque", "Apito"], tipagem="B−",
      descricao="Manda no ferro e no gato de luz de meia cidade. Negocia antes de brigar — e ganha nos dois."),
    C("Leão de Chácara", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Intimidação", "A"), ("Atletismo", "A"), ("Sociedades", "A"), ("Acrobacia", "A")],
      [A("Manopla")], INV(armadura="Armadura Leve", consumiveis=["Poção da Coragem"], ouro=1, tier=1),
      mod="Competente", org="[[Ordem dos Subsolos]]", bairros=["[[Quarto Distrito]]", "[[Bom Fim]]"],
      habilidades=["Bruto Aterrorizador", "Parede de Escudo"], tipagem="O−",
      descricao="Segura a porta do Teatro Quarto Distrito. O corredor é estreito de propósito."),
    C("Agulha da Ordem", 2, "Assassino", "AGI", 2, 3, 1, 0,
      [("Furtividade", "E"), ("Malandragem", "E"), ("Acrobacia", "A"), ("Enganação", "A"), ("Sociedades", "A")],
      [A("Punhal", "Imbuição Congelante", 2), A("Adaga")],
      INV(tesouros=["Capa Discreta"], consumiveis=["Poção da Velocidade"] * 2, ouro=9, tier=2),
      mod="Competente", org="[[Ordem dos Subsolos]]", bairros=["[[Quarto Distrito]]"],
      habilidades=["Alvo de Assassinato", "Pelo Telhado"], tipagem="A−",
      descricao="Mata no meio da festa e sai dançando. Ninguém vê, ninguém fala."),
    C("Estivador de Confiança", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sobrevivência", "A"), ("Malandragem", "A"), ("Sociedades", "A")],
      [A("Maça Estrela"), A("Alabarda")],
      INV(armadura="Armadura Leve", ouro=1, tier=1),
      org="[[Consórcio das Bandeiras]]", bairros=["[[Praia de Belas]]", "[[Lago Guaíba]]"],
      tipagem="O−", descricao="Briga de gancho e corrente no cais. Conhece cada contêiner do Porto Novo."),
    C("Chefe de Armazém", 2, "Líder", "PRE", 2, 0, 1, 3,
      [("Sociedades", "E"), ("Intimidação", "E"), ("Malandragem", "A"), ("Guerra", "A"), ("Diplomacia", "A")],
      [A("Alfange", "Arma Obra-prima", 2)],
      INV(armadura="Armadura Leve", tesouros=["Colar da Eloquência"],
          consumiveis=["Poção de Cura"], ouro=12, tier=2),
      mod="Competente", org="[[Consórcio das Bandeiras]]", bairros=["[[Praia de Belas]]"],
      habilidades=["Ordem de Ataque", "Apito"], tipagem="A−",
      descricao="Comanda a descarga — e a emboscada que espera do outro lado dela."),
    C("Segurança do Cartel dos Eixos", 0, "Soldado", "FOR", 3, 2, 1, 0,
      [("Atletismo", "A"), ("Malandragem", "A"), ("Sobrevivência", "A"), ("Intimidação", "A")],
      [A("Azagaia"), A("Porrete")], INV(tier=0),
      org="[[Cartel dos Eixos]]", bairros=["[[Passo D'Areia]]"], tipagem="B−",
      descricao="Chapa de oficina que não quer conversa: a ferramenta na mão dele já é arma."),
    C("Piloto de Racha", 1, "Batedor", "AGI", 1, 3, 1, 1,
      [("Acrobacia", "A"), ("Atletismo", "A"), ("Malandragem", "A"), ("Sobrevivência", "A"), ("Sociedades", "A")],
      [A("Adaga de Duelo")],
      INV(tesouros=["Botas Fluídicas"], consumiveis=["Poção da Velocidade"], ouro=2, tier=1),
      mod="Competente", org="[[Cartel dos Eixos]]", bairros=["[[Passo D'Areia]]", "[[Nova Sarandi]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="O−",
      descricao="Entra e sai da cena. Metade da briga acontece em movimento."),
    C("Instalador Pirata", 1, "Encantador", "INT", 0, 1, 3, 2,
      [("Trônicos", "A"), ("Medicina", "A"), ("Malandragem", "A"), ("Sociedades", "A"),
       ("Enganação", "A"), ("Diplomacia", "A"), ("Acrobacia", "A")],
      [A("Adaga", "Imbuição Incendiária", 1)],
      INV(tesouros=["Luva do Arcanista"], consumiveis=["Poção da Coragem"], ouro=3, tier=1),
      mod="Competente", org="[[Círculo das Ligas]]", bairros=["[[Petrópolis]]", "[[Quarto Distrito]]"],
      habilidades=["Dose no Braço"], tipagem="AB−", linha_magia="Arcana Branca",
      descricao="Liga módulo no capanga no meio da luta. Sem garantia: às vezes o capanga é que apaga."),
    C("Capanga de Oficina", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Guerra", "A"), ("Sobrevivência", "A")],
      [A("Picareta de Guerra")], INV(armadura="Armadura Leve", ouro=1, tier=1),
      org="[[Círculo das Ligas]]", bairros=["[[Petrópolis]]"],
      habilidades=["Vigor Bruto"], tipagem="A−",
      descricao="Protege a bancada com o que estava em cima dela."),
    C("Refinador", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Lênicos", "A"), ("Medicina", "A"), ("Sobrevivência", "A"), ("Malandragem", "A"), ("Atletismo", "A")],
      [A("Besta Leve"), A("Alfange")],
      INV(tesouros=["Bracelete Elemental"], consumiveis=["Poção da Nutrição"] * 2, ouro=2, tier=1),
      org="[[Comando Itu-Química]]", bairros=["[[Jardim Itu]]"],
      habilidades=["Tiro de Cobertura"], tipagem="O+", linha_magia="Anima", elemento="Fogo",
      descricao="Frasco, vapor e queimadura. Luta como quem despeja, não como quem golpeia."),
    C("Guarda de Refino", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Guerra", "A"), ("Intimidação", "A"), ("Sobrevivência", "A"), ("Medicina", "A")],
      [A("Espada Longa")], INV(armadura="Armadura Leve", consumiveis=["Poção da Nutrição"], ouro=1, tier=1),
      mod="Competente", org="[[Comando Itu-Química]]", bairros=["[[Jardim Itu]]"],
      habilidades=["Restringir Movimento"], tipagem="B−",
      descricao="Tropa de fábrica tomada. Turno de doze horas e nenhum sindicato."),
    C("Biopirata", 1, "Batedor", "AGI", 1, 3, 1, 1,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Acrobacia", "A"), ("Medicina", "A"), ("Lênicos", "A")],
      [A("Machadinha"), A("Adaga")],
      INV(tesouros=["Cinto dos Ermos"], consumiveis=["Poção da Velocidade"], ouro=2, tier=1),
      org="[[Liga da Estufa]]", bairros=["[[Jardim Botânico]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="A−",
      descricao="Furta semente da Estufa Histórica e some pelo mato antes do alarme."),
    C("Envenenador", 2, "Supressor", "INT", 0, 1, 3, 2,
      [("Medicina", "E"), ("Lênicos", "E"), ("Furtividade", "A"), ("Sobrevivência", "A"),
       ("Malandragem", "A"), ("Trônicos", "A"), ("Enganação", "A")],
      [A("Besta de Mão", "Imbuição Enraizante", 2), A("Punhal")],
      INV(tesouros=["Luvas Purificadas"], consumiveis=["Poção da Nutrição"] * 2, ouro=9, tier=2),
      mod="Competente", org="[[Liga da Estufa]]", bairros=["[[Jardim Botânico]]", "[[Moinhos de Vento]]"],
      habilidades=["Restringir Movimento", "Queimar a Rota"], tipagem="B−", linha_magia="Arcana Negra",
      descricao="Tira o herói da luta sem matar. O grupo perde alguém por três rodadas — e o resto vira número."),
    C("Escolta Particular", 2, "Assassino", "AGI", 2, 3, 1, 0,
      [("Acrobacia", "E"), ("Sociedades", "E"), ("Furtividade", "A"), ("Diplomacia", "A"), ("Enganação", "A")],
      [A("Rapieira", "Arma Obra-prima", 2), A("Punhal")],
      INV(tesouros=["Anel do Equilíbrio"], consumiveis=["Poção de Cura"], ouro=14, tier=2),
      mod="Competente", org="[[Sociedade dos Jardins]]", bairros=["[[Moinhos de Vento]]", "[[Ipanema]]"],
      habilidades=["Alvo de Assassinato"], tipagem="A−",
      descricao="Esgrima de clube e terno de alfaiate. Atira primeiro por educação."),
    C("Corretor de Chantagem", 2, "Encantador", "INT", 0, 1, 3, 2,
      [("Sociedades", "E"), ("Enganação", "E"), ("Diplomacia", "A"), ("Trônicos", "A"),
       ("Malandragem", "A"), ("Medicina", "A"), ("Acrobacia", "A")],
      [A("Punhal")], INV(tesouros=["Colar da Eloquência"], consumiveis=["Poção da Coragem"], ouro=20, tier=2),
      mod="Competente", org="[[Sociedade dos Jardins]]", bairros=["[[Moinhos de Vento]]"],
      habilidades=["Dose no Braço"], tipagem="AB−", linha_magia="Arcana Branca",
      descricao="A arma dele é o dossiê. Vira aliado do grupo contra o grupo."),
    C("Miliciano da Estrada", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Sobrevivência", "A"), ("Guerra", "A"), ("Intimidação", "A"), ("Atletismo", "A"), ("Sociedades", "A")],
      [A("Espada Curva")], INV(armadura="Armadura Leve", ouro=2, tier=1),
      org="[[Movimento Restinga Livre]]", bairros=["[[Restinga]]"], tipagem="O−",
      descricao="A guarita da estrada única. Decide quem entra — em dólar."),
    C("Guarita da Restinga", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Lênicos", "A"), ("Guerra", "A"), ("Atletismo", "A")],
      [A("Funda"), A("Espada Curva")],
      INV(tesouros=["Amplificador Audiovisual"], ouro=1, tier=1),
      org="[[Movimento Restinga Livre]]", bairros=["[[Restinga]]"],
      habilidades=["Tiro de Cobertura"], tipagem="A+", linha_magia="Anima", elemento="Terra",
      descricao="Fogo de cobertura da Torre de Vigilância Caseira. Improvisa munição com o que o mercado tem."),
    C("Ex-Praça", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Guerra", "A"), ("Atletismo", "A"), ("Intimidação", "A"), ("Sobrevivência", "A"), ("Medicina", "A")],
      [A("Espada Curta"), A("Porrete")],
      INV(armadura="Armadura Leve", consumiveis=["Poção de Cura"], ouro=2, tier=1),
      mod="Competente", org="[[Consórcio Paraguassu]]", bairros=["[[Costa e Silva]]"],
      habilidades=["Restringir Movimento", "Parede de Escudo"], tipagem="A−",
      descricao="Treinamento de quartel, moral de milícia. Sabe exatamente o que a Brigada vai fazer."),
    C("Miliciano Veterano", 2, "Bruto", "FOR", 3, 2, 0, 1,
      [("Guerra", "E"), ("Intimidação", "E"), ("Atletismo", "A"), ("Sobrevivência", "A")],
      [A("Machado de Batalha", "Arma Obra-prima", 2)],
      INV(armadura="Armadura Leve", tesouros=["Diadema da Ameaça"],
          consumiveis=["Poção da Coragem"], ouro=8, tier=2),
      mod="Competente", org="[[Consórcio Paraguassu]]", bairros=["[[Costa e Silva]]", "[[Zona Deserta]]"],
      habilidades=["Bruto Aterrorizador", "Casco"], tipagem="O−",
      descricao="O que sobrou da tropa, pior e mais livre. Não tem regulamento pra segurar."),
    C("Segurança de Condomínio", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Sociedades", "A"), ("Intimidação", "A"), ("Atletismo", "A"), ("Guerra", "A"), ("Diplomacia", "A")],
      [A("Porrete")], INV(armadura="Armadura Leve", escudo="Broquel", ouro=2, tier=1),
      mod="Competente", org="[[Clube dos Sete Portos]]", bairros=["[[Ipanema]]", "[[Moinhos de Vento]]"],
      habilidades=["Parede de Escudo"], tipagem="A−",
      descricao="Barra na guarita e atira do muro. Educadíssimo com quem tem sobrenome."),
    C("Chefe de Segurança", 2, "Líder", "PRE", 2, 0, 1, 3,
      [("Sociedades", "E"), ("Guerra", "E"), ("Diplomacia", "A"), ("Intimidação", "A"), ("Enganação", "A")],
      [A("Pistola Arcanônica", "Arma Obra-prima", 2), A("Espada Curta")],
      INV(armadura="Armadura Leve", tesouros=["Anel Mensageiro"],
          consumiveis=["Poção de Cura"], ouro=18, tier=2),
      mod="Competente", org="[[Clube dos Sete Portos]]", bairros=["[[Ipanema]]"],
      habilidades=["Ordem de Ataque", "Fechar Formação"], tipagem="O−",
      descricao="Coordena as escoltas pelo rádio — e some quando a coisa aperta."),
    C("Saqueador de Vagão", 1, "Batedor", "AGI", 2, 3, 1, 0,
      [("Atletismo", "A"), ("Acrobacia", "A"), ("Malandragem", "A"), ("Sobrevivência", "A"), ("Guerra", "A")],
      [A("Tacape"), A("Adaga de Duelo")],
      INV(tesouros=["Braceletes de Pedra"], ouro=1, tier=1),
      org="[[Confraria dos Trilhos]]", bairros=["[[Nova Sarandi]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="B−",
      descricao="Ataca em movimento na Ferroviária Nacional: sobe, leva e pula."),
    C("Boêmio Armado", 0, "Batedor", "AGI", 1, 3, 1, 1,
      [("Malandragem", "A"), ("Acrobacia", "A"), ("Sociedades", "A"), ("Enganação", "A")],
      [A("Adaga")], INV(tier=0), org="[[Irmandade do Café Preto]]", bairros=["[[Bom Fim]]"],
      tipagem="AB−", descricao="Briga de bar do Bar Ocidente que vira perseguição por três quarteirões."),
    C("Representante da Camisa 12", 0, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sociedades", "A")],
      [A("Bordão"), A("Manopla")], INV(tier=0),
      org="[[Camisa 12]]", bairros=["[[Praia de Belas]]", "[[Jardim Botânico]]"], tipagem="O−",
      descricao="Vem em bando. Sozinho não é nada — e é por isso que nunca vem sozinho."),
    C("Cabeça de Torcida", 1, "Líder", "PRE", 2, 0, 1, 3,
      [("Intimidação", "A"), ("Sociedades", "A"), ("Atletismo", "A"), ("Malandragem", "A"), ("Diplomacia", "A")],
      [A("Maça Estrela")], INV(armadura="Armadura Leve", tesouros=["Diadema da Ameaça"], ouro=4, tier=1),
      org="[[Camisa 12]]", bairros=["[[Praia de Belas]]", "[[Jardim Botânico]]"],
      habilidades=["Apito", "Não Recuem"], tipagem="O−",
      descricao="Transforma o bando em problema: quem ele aponta, trinta perseguem."),
    C("Piquete", 0, "Bruto", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sociedades", "A"), ("Guerra", "A")],
      [A("Azagaia")], INV(tier=0), org="[[Sindicato dos Metalúrgicos]]",
      bairros=["[[Petrópolis]]", "[[Nova Sarandi]]"], habilidades=["Parede de Escudo"], tipagem="A−",
      descricao="Barra a Rua das Indústrias na greve. Não quer machucar — mas ninguém passa."),
    C("Sabotador", 1, "Supressor", "INT", 0, 2, 3, 1,
      [("Trônicos", "A"), ("Malandragem", "A"), ("Furtividade", "A"), ("Sociedades", "A"),
       ("Enganação", "A"), ("Acrobacia", "A"), ("Medicina", "A")],
      [A("Adaga de Duelo")], INV(tesouros=["Luvas do Ladrão"], consumiveis=["Poção da Coragem"], ouro=1, tier=1),
      org="[[Resistência Urbana Gaúcha]]", bairros=["[[Bom Fim]]", "[[Quarto Distrito]]", "[[Centro Histórico]]"],
      habilidades=["Restringir Movimento", "Queimar a Rota"], tipagem="B−", linha_magia="Arcana Negra",
      descricao="Apaga a luz e o sinal. Costuma ser aliado — até o grupo aceitar serviço da firma errada."),
    C("Agulha de Beco", 0, "Assassino", "AGI", 1, 3, 1, 1,
      [("Furtividade", "A"), ("Malandragem", "A"), ("Acrobacia", "A"), ("Enganação", "A")],
      [A("Punhal")], INV(tier=0), org="", bairros=["[[Restinga]]", "[[Cidade Baixa]]", "[[Quarto Distrito]]"],
      habilidades=["Alvo de Assassinato"], tipagem="O−",
      descricao="O punguista que vira faca quando é pego."),
    C("Chefe de Esquina", 0, "Líder", "PRE", 2, 0, 1, 3,
      [("Intimidação", "A"), ("Sociedades", "A"), ("Malandragem", "A"), ("Enganação", "A")],
      [A("Manopla")], INV(ouro=1, tier=0), org="",
      bairros=["[[Restinga]]", "[[Cidade Baixa]]", "[[Quarto Distrito]]", "[[Jardim Itu]]"],
      habilidades=["Apito"], tipagem="B−",
      descricao="O primeiro 'chefe' que o grupo enfrenta, em qualquer bairro pobre. Manda em seis."),
    C("O Despachante", 3, "Assassino", "AGI", 2, 3, 1, 0,
      [("Furtividade", "M"), ("Malandragem", "M"), ("Acrobacia", "E"), ("Sociedades", "E"), ("Enganação", "A")],
      [A("Espada Bastarda", "Imbuição de Aço Solar", 3), A("Punhal")],
      INV(armadura="Armadura Leve", tesouros=["Capa Discreta"],
          consumiveis=["Poção da Velocidade"] * 2, ouro=50, tier=3),
      mod="Solo", org="[[A Caixinha]]", bairros=["[[Porto Alegre]]"],
      habilidades=["Alvo de Assassinato", "Oportunista", "Pelo Telhado"], tipagem="A−",
      descricao="Quem cobra a conta de quem trai a Caixinha. Nenhum registro em lugar nenhum."),
]

CRIATURAS += [
    # ─────────────────────────── Não-gente ───────────────────────────
    C("Rato-do-Delta", 0, "Batedor", "AGI", 1, 3, 0, 2,
      [("Furtividade", "A"), ("Acrobacia", "A"), ("Sobrevivência", "A")],
      [A("Presas de Lobo")], INV(tier=0), org="", bairros=["[[Delta Radioativo]]", "[[Cidade Baixa]]"],
      habilidades=["Oportunista"], tipagem="—", raca=INCOMUM, tamanho="Pequeno",
      descricao="Vem em dezenas pela Rua do Rato. Cada um é troco; o problema é a quantidade."),
    C("Cão Mutante", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Sobrevivência", "A"), ("Furtividade", "A"), ("Intimidação", "A")],
      [A("Garra de Tigre")], INV(tier=1), org="", bairros=["[[Delta Radioativo]]", "[[Zona Deserta]]"],
      habilidades=["Bruto Aterrorizador"], tipagem="—", raca=INCOMUM,
      descricao="Investe e derruba. A pele descascada não é ferida: é o que a chuva ácida fez."),
    C("Coisa da Lagoa", 2, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "E"), ("Sobrevivência", "E"), ("Intimidação", "A"), ("Furtividade", "A")],
      [A("Cauda", "Imbuição Hidratante", 2)], INV(ouro=25, tier=2),
      mod="Solo", org="", bairros=["[[Delta Radioativo]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Grande",
      descricao="O que o depósito tóxico a céu aberto fez com algo que já foi bicho."),
    C("Colônia Mutante", 3, "Supressor", "INT", 1, 0, 3, 2,
      [("Sobrevivência", "M"), ("Furtividade", "M"), ("Lênicos", "E"), ("Atletismo", "E"),
       ("Medicina", "A"), ("Acrobacia", "A"), ("Trônicos", "A")],
      [A("Cauda Colossal", "Imbuição Enraizante", 3)], INV(ouro=30, tier=3),
      mod="Solo", org="", bairros=["[[Delta Radioativo]]"],
      habilidades=["Restringir Movimento", "Queimar a Rota", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Enorme", linha_magia="Arcana Negra",
      descricao="Não é um bicho: é a estação inteira. O chão prende, o ar consome."),
    C("Drone de Guarda", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Trônicos", "A"), ("Furtividade", "A"), ("Guerra", "A"), ("Acrobacia", "A"), ("Lênicos", "A")],
      [A("Besta")], INV(tesouros=["Sensor Arcano"], tier=1),
      org="[[Complexo de Testes Orion]]", bairros=["[[Zona Deserta]]"],
      habilidades=["Tiro de Cobertura"], tipagem="A+", linha_magia="Anima", elemento="Terra",
      raca=INCOMUM, tamanho="Pequeno",
      descricao="Torre voadora com dardo. Sobe fora de alcance, atira e volta."),
    C("Drone Sequestrado", 1, "Batedor", "AGI", 0, 3, 2, 1,
      [("Acrobacia", "A"), ("Furtividade", "A"), ("Trônicos", "A"), ("Guerra", "A"),
       ("Malandragem", "A"), ("Sociedades", "A")],
      [A("Besta de Mão")], INV(tesouros=["Anel Mensageiro"], tier=1),
      org="[[Base Fantasma]]", bairros=["[[Zona Deserta]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="—", raca=INCOMUM, tamanho="Pequeno",
      descricao="Responde a quem gritar mais alto no rádio. Vira contra quem o chamou."),
    C("Androide de Vigilância", 2, "Soldado", "FOR", 3, 1, 2, 0,
      [("Guerra", "E"), ("Furtividade", "E"), ("Atletismo", "A"), ("Trônicos", "A"),
       ("Acrobacia", "A"), ("Sociedades", "A")],
      [A("Espada Curta", "Arma Obra-prima", 2)],
      INV(armadura="Armadura Pesada", tesouros=["Amplificador Audiovisual"], ouro=40, tier=2),
      mod="Elite", org="[[Complexo de Testes Orion]]", bairros=["[[Zona Deserta]]", "[[Delta Radioativo]]"],
      habilidades=["Restringir Movimento", "Casco"], tipagem="—", raca=INCOMUM,
      descricao="Continua cumprindo uma ordem que ninguém lembra de ter dado."),
    C("Protótipo Orion", 3, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "M"), ("Intimidação", "M"), ("Guerra", "E"), ("Acrobacia", "E")],
      [A("Cauda Colossal", "Imbuição Explosiva", 3)],
      INV(armadura=("Armadura Pesada", "Armadura Obra-prima"), tier=3),
      mod="Solo", org="[[Complexo de Testes Orion]]", bairros=["[[Zona Deserta]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Enorme",
      descricao="O chefão do fim da linha, no subsolo da Zona Deserta. Foi feito pra não ser desligado."),
    C("Corredor Fantasma", 3, "Batedor", "AGI", 1, 3, 2, 0,
      [("Acrobacia", "M"), ("Furtividade", "M"), ("Atletismo", "E"), ("Trônicos", "E"),
       ("Guerra", "A"), ("Malandragem", "A")],
      [A("Garra de Tigre", "Imbuição Ciclonal", 3)], INV(tesouros=["Botas Fluídicas"], tier=3),
      mod="Solo", org="[[Base Fantasma]]", bairros=["[[Zona Deserta]]", "[[Delta Radioativo]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="—", raca=INCOMUM,
      descricao="Rápido demais pra cercar. Some do sinal e reaparece atrás da fila."),
    C("Bateria da Torre", 3, "Artilharia", "PRE", 0, 1, 2, 3,
      [("Guerra", "M"), ("Lênicos", "M"), ("Furtividade", "E"), ("Trônicos", "E"),
       ("Atletismo", "A"), ("Acrobacia", "A")],
      [A("Besta", "Imbuição da Ventania", 3)], INV(tesouros=["Bracelete Elemental"], tier=3),
      mod="Elite", org="[[Embratel]]", bairros=["[[Costa e Silva]]", "[[Moinhos de Vento]]"],
      habilidades=["Tiro de Cobertura"], tipagem="B+", linha_magia="Anima", elemento="Vento",
      raca=INCOMUM, tamanho="Grande",
      descricao="A torre de escuta que também atira. Cobre o bairro inteiro e nunca está onde o grupo está."),
]
