"""Especificação das criaturas da POA 1987 — fonte única do gerador.

Convenções (documentadas no rascunho do bestiário):
  · categoria do tesouro segue o tier: T0/T1 Adepto, T2 Experiente, T3 Mestre
  · Artilharia é sempre Fator positivo (Lênica é química do sangue) e o Fator
    vira a Sintonia: O+ Fogo · A+ Terra · B+ Vento · AB+ Água
  · quem tem arma a distância leva backup corpo-a-corpo (exceto sem-mão)
  · pólvora (Bacamarte/Pistola Arcanônica) só com contrato estatal
"""

# Tipagem → nota de `categoria: Sintonia`. Os Fatores POSITIVOS são os Traços
# Elementais do sistema (o reskin já os exibe como "Fator X+"); os NEGATIVOS e
# as duas trônicas são notas próprias da POA (Sintonia/Tipagens).
SINTONIA = {
    "O+": "[[Traço Elemental do Fogo]]",
    "A+": "[[Traço Elemental da Terra]]",
    "B+": "[[Traço Elemental do Vento]]",
    "AB+": "[[Traço Elemental da Água]]",
    "O−": "[[Fator O Negativo]]",
    "A−": "[[Fator A Negativo]]",
    "B−": "[[Fator B Negativo]]",
    "AB−": "[[Fator AB Negativo]]",
    "Positrônico": "[[Fator Positrônico]]",
    "Negatrônico": "[[Fator Negatrônico]]",
}
CAT_POR_TIER = {0: "Adepto", 1: "Adepto", 2: "Experiente", 3: "Mestre"}

# ── magias por linha e elemento (nomes canônicos do Sistema) ──────────────────
LENICA = {
    "Fogo": ["Raio Flamejante", "Estouro", "Coluna de Fogo", "Cone de Fogo", "Combustão",
             "Bola de Fogo", "Manto Incendiário"],
    "Terra": ["Pulso Sísmico", "Escudo Rochoso", "Barreira de Pedra", "Onda de Choque",
              "Tremor", "Rocha Empaladora", "Pele de Pedra"],
    "Vento": ["Corte de Vento", "Vento Mensageiro", "Lufada de Vento", "Vento Guardião",
              "Passos do Vento", "Pressurização Repentina", "Propulsão Explosiva"],
    "Água": ["Esfera d'Água", "Frio Instantâneo", "Atadura d'Água", "Rajada d'água",
             "Caminho de Gelo", "Hidrovitalizar", "Onda d'água", "Cristalização Gélida"],
}
POSITRONICA = ["Guiar", "Proteger", "Avivar", "Celeridade", "Empoderar", "Encantar Arma",
               "Melhorar Habilidade", "Passos Rápidos", "Aceleração", "Heroísmo",
               "Regeneração", "Aceleração em Massa"]
NEGATRONICA = ["Aturdir", "Choque Mental", "Drenar", "Enfraquecer", "Entorpecer",
               "Aterrorizar", "Ofuscação", "Míssil Mágico", "Lentidão", "Confusão",
               "Distorção Sensorial", "Sifão Vital", "Condenar", "Lentidão em Massa"]


def magias(linha: str, tier: int, elemento: str | None = None) -> list[str]:
    """Quantidade por tier (espelha o Goblin Piromante, Artilharia T1 = 4)."""
    n = {0: 3, 1: 4, 2: 5, 3: 6}[tier]
    if linha == "Anima":
        return LENICA[elemento][:n]
    return (POSITRONICA if linha == "Arcana Branca" else NEGATRONICA)[:n]


def A(nome, prop=None, tier=None):
    """Arma: nome canônico + propriedade (módulo/premium) com a categoria do tier."""
    a = {"nome": nome}
    if prop:
        a["propriedade"] = prop
        a["categoria"] = CAT_POR_TIER[tier]
    return a


def INV(armadura=None, escudo=None, tesouros=(), consumiveis=(), ouro=0, tier=0):
    inv = {"tesouros": list(tesouros), "consumiveis": list(consumiveis), "ouro": ouro}
    if armadura:
        nome, prop = (armadura if isinstance(armadura, tuple) else (armadura, None))
        inv["armadura"] = {"nome": nome, "categoria": CAT_POR_TIER[tier] if prop else "",
                           "propriedade": prop}
    if escudo:
        nome, prop = (escudo if isinstance(escudo, tuple) else (escudo, None))
        inv["escudo"] = {"nome": nome, "categoria": CAT_POR_TIER[tier] if prop else "",
                         "propriedade": prop,
                         "dano": 4 if nome == "Escudo" else 2,
                         "dureza": 5 if nome == "Escudo" else 3}
    return inv


def C(nome, tier, papel, principal, F, Ag, I, P, pericias, armas, inventario, *,
      mod=None, org="", bairros=(), habilidades=(), tipagem="O−", linha_magia=None,
      elemento=None, raca=None, tamanho="Médio", descricao="", aliases=()):
    spec = {
        "nome": nome, "tier": tier, "papel": papel, "mod": mod, "principal": principal,
        "atributos": {"FOR": F, "AGI": Ag, "INT": I, "PRE": P},
        "pericias": pericias, "armas": armas, "inventario": inventario,
        "habilidades": list(habilidades), "org": org, "bairros": list(bairros),
        "tipagem": tipagem, "descricao": descricao, "aliases": list(aliases),
        "tamanho": tamanho,
    }
    if raca:
        spec["raca"] = raca
    if linha_magia:
        spec["linha_magia"] = linha_magia
        spec["magias"] = magias(linha_magia, tier, elemento)
    # Encantador e Supressor não operam por sangue: operam por IMPLANTE — a
    # tipagem deles é a linha trônica que rodam, não o Fator do RG.
    if papel == "Encantador":
        tipagem = "Positrônico"
    elif papel == "Supressor":
        tipagem = "Negatrônico"
    if tipagem in SINTONIA:
        spec["sintonia"] = SINTONIA[tipagem]
    spec["tipagem"] = tipagem
    return spec


B = "[[Brigada Militar Metropolitana]]"
INCOMUM = "[[Incomum|Incomum]]"

CRIATURAS = [
    # ─────────────────────────── Estado ───────────────────────────
    C("Brigadiano de Esquina", 0, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Guerra", "A"), ("Sociedades", "A")],
      [A("Porrete")], INV(tier=0), org=B, bairros=["[[Porto Alegre]]"],
      descricao="A dupla de farda que para o herói na calçada e pede o laudo. Sozinho não resolve nada; o problema é o rádio no ombro."),
    C("Cão de Brigada", 0, "Batedor", "AGI", 2, 3, 0, 1,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Atletismo", "A")],
      [A("Presas de Lobo")], INV(tier=0), org=B, bairros=["[[Porto Alegre]]"],
      habilidades=["Restringir Movimento", "Farejar Dose"], tipagem="—",
      raca=INCOMUM, descricao="Fareja dose e sangue. Prende o herói no lugar até a farda chegar."),
    C("Brigadiano Atirador", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Furtividade", "A"), ("Guerra", "A"), ("Atletismo", "A"), ("Lênicos", "A"), ("Sociedades", "A")],
      [A("Besta de Mão"), A("Adaga")],
      INV(armadura="Armadura Leve", consumiveis=["Poção de Cura", "Poção de Cura"], ouro=2, tier=1),
      org=B, bairros=["[[Porto Alegre]]"], habilidades=["Tiro de Cobertura"],
      tipagem="B+", linha_magia="Anima", elemento="Vento",
      descricao="O bico de brigadiano: sem farda, com dardo selênico e um nome que ninguém anota."),
    C("Cabo de Choque", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Guerra", "A"), ("Acrobacia", "A"), ("Sociedades", "A")],
      [A("Porrete", "Imbuição Sísmica", 1), A("Escudada")],
      INV(armadura="Armadura Leve", escudo="Escudo", consumiveis=["Poção da Coragem"], ouro=1, tier=1),
      mod="Competente", org=B, bairros=["[[Centro Histórico]]", "[[Bom Fim]]", "[[Cidade Baixa]]"],
      habilidades=["Restringir Movimento", "Parede de Escudo"], tipagem="A−",
      descricao="Formação de escudo da Operação Silêncio. Empurra, prensa na parede e não deixa passar."),
    C("Atirador de Torre", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Guerra", "A"), ("Furtividade", "A"), ("Atletismo", "A"), ("Lênicos", "A"), ("Sobrevivência", "A")],
      [A("Besta Leve"), A("Espada Curta")],
      INV(tesouros=["Amplificador Audiovisual", "Diapasão Elemental"], consumiveis=["Poção de Cura"], ouro=2, tier=1),
      org=B, bairros=["[[Restinga]]", "[[Zona Deserta]]", "[[Quarto Distrito]]"],
      habilidades=["Tiro de Cobertura"], tipagem="O+", linha_magia="Anima", elemento="Fogo",
      descricao="Fica na guarita e queima a rua de longe. Some quando o herói chega perto."),
    C("Piloto de Anfíbio", 1, "Batedor", "AGI", 2, 3, 1, 0,
      [("Atletismo", "A"), ("Acrobacia", "A"), ("Sobrevivência", "A"), ("Guerra", "A"), ("Malandragem", "A")],
      [A("Porrete"), A("Lança")],
      INV(armadura="Armadura Leve", consumiveis=["Poção da Velocidade"], ouro=1, tier=1),
      org=B, bairros=["[[Cidade Baixa]]", "[[Praia de Belas]]", "[[Lago Guaíba]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="B−",
      descricao="Chega pela água na tocaia da Cidade Baixa. Dirige, atropela e recua."),
    C("Sargento de Pelotão", 2, "Líder", "PRE", 2, 0, 1, 3,
      [("Guerra", "E"), ("Intimidação", "E"), ("Sociedades", "A"), ("Atletismo", "A"), ("Diplomacia", "A")],
      [A("Espada Curta", "Arma Obra-prima", 2), A("Porrete")],
      INV(armadura="Armadura Leve", tesouros=["Brasão Tático"],
          consumiveis=["Poção de Cura", "Poção de Cura"], ouro=8, tier=2),
      mod="Competente", org=B, bairros=["[[Porto Alegre]]"],
      habilidades=["Ordem de Ataque", "Não Recuem"], tipagem="A−",
      descricao="Não é o mais forte: é o que faz os outros oito valerem por dezesseis. Mata-se ele primeiro."),
    C("Franco-Atirador da Brigada", 2, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Furtividade", "E"), ("Guerra", "E"), ("Atletismo", "A"), ("Lênicos", "A"), ("Acrobacia", "A")],
      [A("Besta", "Arma Obra-prima", 2), A("Arco Longo"), A("Adaga")],
      INV(tesouros=["Capa Discreta"], consumiveis=["Poção da Velocidade"] * 3, ouro=6, tier=2),
      mod="Competente", org=B, bairros=["[[Centro Histórico]]", "[[Moinhos de Vento]]", "[[Petrópolis]]"],
      habilidades=["Tiro de Cobertura", "Alvo de Assassinato"], tipagem="B+",
      linha_magia="Anima", elemento="Vento",
      descricao="Dardo selênico do telhado. Escolhe um alvo por rodada e pune quem se expõe."),
    C("Exoesqueleto do BOPE", 2, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "E"), ("Intimidação", "E"), ("Guerra", "A"), ("Acrobacia", "A")],
      [A("Machadão", "Imbuição Mineral", 2)],
      INV(armadura="Armadura Pesada", tesouros=["Pulseira da Potência"],
          consumiveis=["Poção da Coragem", "Poção da Coragem"], ouro=10, tier=2),
      mod="Elite", org=B, bairros=["[[Petrópolis]]", "[[Passo D'Areia]]", "[[Nova Sarandi]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="A−",
      descricao='O "bope corporativo": casco Tramontina e rádio Gradiente. O muro que entra na frente.'),
    C("Pelotão de Guarnição", 3, "Soldado", "FOR", 3, 1, 1, 1,
      [("Guerra", "M"), ("Atletismo", "M"), ("Intimidação", "E"), ("Sociedades", "E"), ("Medicina", "A")],
      [A("Bacamarte Arcanônico"), A("Espada Curta", "Arma Obra-prima", 3)],
      INV(armadura="Armadura Pesada", escudo="Escudo",
          consumiveis=["Poção de Cura", "Poção de Cura"], ouro=20, tier=3),
      mod="Elite", org="[[Governo Militar Brasileiro]]", bairros=["[[Costa e Silva]]", "[[Zona Deserta]]"],
      habilidades=["Restringir Movimento", "Parede de Escudo"], tipagem="O−",
      descricao="Tropa de quartel, com pólvora legal. Não negocia e não corre."),
    C("Oficial de Operações", 3, "Líder", "PRE", 1, 0, 2, 3,
      [("Guerra", "M"), ("Diplomacia", "M"), ("Sociedades", "E"), ("Intimidação", "E"),
       ("Enganação", "A"), ("Malandragem", "A")],
      [A("Pistola Arcanônica"), A("Espada Curta", "Arma Obra-prima", 3)],
      INV(armadura=("Armadura Pesada", "Armadura Obra-prima"), tesouros=["Anel Mensageiro"],
          consumiveis=["Poção de Cura", "Poção de Cura"], ouro=40, tier=3),
      mod="Solo", org="[[Governo Militar Brasileiro]]", bairros=["[[Costa e Silva]]", "[[Centro Histórico]]"],
      habilidades=["Ordem de Ataque", "Fechar Formação", "Não Recuem"], tipagem="A−",
      descricao="Coordena toque de recolher e apoio aéreo: a cena inteira é ele."),
    C("Coronel Luciana Prado", 3, "Líder", "PRE", 1, 0, 2, 3,
      [("Guerra", "M"), ("Intimidação", "M"), ("Diplomacia", "E"), ("Sociedades", "E"),
       ("Enganação", "A"), ("Malandragem", "A")],
      [A("Pistola Arcanônica"), A("Espada Curta", "Imbuição de Ferro Frio", 3)],
      INV(armadura=("Armadura Pesada", "Armadura Obra-prima"), tesouros=["Brasão Tático"],
          consumiveis=["Poção de Cura"] * 3, ouro=50, tier=3),
      mod="Solo", org=B, bairros=["[[Centro Histórico]]", "[[Bom Fim]]"],
      habilidades=["Ordem de Ataque", "Não Recuem", "Alvo de Assassinato"], tipagem="AB−",
      aliases=["Coronel Prado"],
      descricao="Quem assina a Operação Silêncio. Não aparece em batida: aparece quando a batida deu errado."),
]

CRIATURAS += [
    # ─────────────────────── Megacorporações ───────────────────────
    C("Segurança de Crachá", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sociedades", "A"), ("Guerra", "A"), ("Diplomacia", "A")],
      [A("Porrete")], INV(armadura="Armadura Leve", ouro=2, tier=1),
      org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]", "[[Ipanema]]", "[[Centro Histórico]]"],
      tipagem="A−", descricao="Porteiro armado de prédio corporativo. Barra quem não tem crachá e chama a Brigada."),
    C("Drone de Vigilância", 1, "Batedor", "AGI", 0, 3, 2, 1,
      [("Furtividade", "A"), ("Acrobacia", "A"), ("Trônicos", "A"), ("Atletismo", "A"), ("Sociedades", "A"), ("Guerra", "A")],
      [A("Besta de Mão")], INV(tesouros=["Amplificador Audiovisual"], tier=1),
      org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]", "[[Ipanema]]", "[[Jardim Botânico]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="—", raca=INCOMUM, tamanho="Pequeno",
      descricao="Vê, marca e chama reforço. Matar é fácil; matar antes de ele transmitir é que é o problema."),
    C("Operador Trônico", 2, "Encantador", "INT", 0, 1, 3, 2,
      [("Trônicos", "E"), ("Sociedades", "E"), ("Enganação", "A"), ("Malandragem", "A"),
       ("Medicina", "A"), ("Diplomacia", "A"), ("Acrobacia", "A")],
      [A("Adaga")], INV(tesouros=["Luva do Arcanista", "Broche Artístico"], consumiveis=["Poção da Coragem"] * 2, ouro=12, tier=2),
      mod="Competente", org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]", "[[Centro Histórico]]"],
      habilidades=["Dose no Braço"], tipagem="AB−", linha_magia="Arcana Branca",
      descricao="Roda rotina nos próprios colegas: o capanga ao lado dele fica melhor do que devia."),
    C("Escolta de Diretoria", 2, "Assassino", "AGI", 2, 3, 0, 1,
      [("Furtividade", "E"), ("Acrobacia", "E"), ("Atletismo", "A"), ("Malandragem", "A")],
      [A("Pistola Arcanônica"), A("Punhal", "Arma Obra-prima", 2)],
      INV(armadura="Armadura Leve", tesouros=["Anel Canário"],
          consumiveis=["Poção de Cura"] * 2, ouro=15, tier=2),
      mod="Competente", org="[[Gradiente]]", bairros=["[[Ipanema]]", "[[Moinhos de Vento]]"],
      habilidades=["Alvo de Assassinato"], tipagem="O−",
      descricao="Terno, contrato estatal e porte legal. Escolhe UM da mesa e vai só nele."),
    C("Auditor de Campo", 3, "Supressor", "INT", 0, 1, 3, 2,
      [("Trônicos", "M"), ("Sociedades", "M"), ("Enganação", "E"), ("Malandragem", "E"),
       ("Medicina", "A"), ("Diplomacia", "A"), ("Furtividade", "A")],
      [A("Adaga de Duelo", "Imbuição de Ferro Frio", 3)],
      INV(armadura="Armadura Leve", tesouros=["Luvas do Ladrão"],
          consumiveis=["Poção da Velocidade"] * 2, ouro=35, tier=3),
      mod="Elite", org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]", "[[Petrópolis]]", "[[Nova Sarandi]]"],
      habilidades=["Restringir Movimento", "Queimar a Rota"], tipagem="A−", linha_magia="Arcana Negra",
      descricao="Quando a firma vira inimiga: corta rota, tranca porta e desliga implante de quem tem registro."),
    C("Sistemista da Gradiente", 3, "Encantador", "INT", 0, 1, 3, 2,
      [("Trônicos", "M"), ("Sociedades", "M"), ("Enganação", "E"), ("Diplomacia", "E"),
       ("Malandragem", "A"), ("Medicina", "A"), ("Acrobacia", "A")],
      [A("Punhal", "Arma Obra-prima", 3)],
      INV(tesouros=["Luva do Arcanista", "Foco da Repetição"], consumiveis=["Poção de Cura"] * 3, ouro=60, tier=3),
      mod="Solo", org="[[Gradiente]]", bairros=["[[Moinhos de Vento]]"],
      habilidades=["Dose no Braço", "Fechar Formação"], tipagem="AB−", linha_magia="Arcana Branca",
      descricao="O topo da escada trônica. Não luta: usa a cidade — semáforo, elevador, rádio — como arma."),
    C("Segurança de Portaria", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Guerra", "A"), ("Intimidação", "A"), ("Sociedades", "A"), ("Sobrevivência", "A")],
      [A("Espada Curta", "Arma Obra-prima", 1)],
      INV(armadura="Armadura Leve", ouro=2, tier=1),
      mod="Competente", org="[[Tramontina]]", bairros=["[[Petrópolis]]", "[[Nova Sarandi]]"],
      tipagem="O−", descricao="A firma que fabrica a lâmina também a carrega. Uniforme limpo, faca com número de série."),
    C("Protótipo de Exoesqueleto", 2, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "E"), ("Intimidação", "E"), ("Guerra", "A"), ("Acrobacia", "A")],
      [A("Martelo de Guerra", "Imbuição Sísmica", 2)],
      INV(armadura="Armadura Pesada", tesouros=["Pulseira da Potência"], tier=2),
      mod="Elite", org="[[Tramontina]]", bairros=["[[Petrópolis]]"],
      habilidades=["Vigor Bruto", "Casco"], tipagem="—", raca=INCOMUM, tamanho="Grande",
      descricao="Máquina de teste solta no galpão do Instituto Técnico. Não sabe que parou de ser um exercício."),
    C("Modelo Militar", 3, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "M"), ("Intimidação", "M"), ("Guerra", "E"), ("Acrobacia", "E")],
      [A("Montante", "Imbuição Flamejante", 3)],
      INV(armadura=("Armadura Pesada", "Armadura Obra-prima"), tesouros=["Pulseira da Potência"], tier=3),
      mod="Solo", org="[[Tramontina]]", bairros=["[[Zona Deserta]]", "[[Costa e Silva]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Grande", descricao="A encomenda do regime. O chefão de metal."),
    C("Fiscal de Patente", 1, "Supressor", "INT", 0, 1, 3, 2,
      [("Trônicos", "A"), ("Medicina", "A"), ("Sociedades", "A"), ("Enganação", "A"),
       ("Malandragem", "A"), ("Diplomacia", "A"), ("Furtividade", "A")],
      [A("Porrete")], INV(tesouros=["Luvas Purificadas"], consumiveis=["Poção da Nutrição"] * 2, ouro=3, tier=1),
      org="[[Panvel]]", bairros=["[[Jardim Itu]]", "[[Bom Fim]]", "[[Restinga]]"],
      habilidades=["Queimar a Rota"], tipagem="B−", linha_magia="Arcana Negra",
      descricao="Fecha bancada clandestina. Não bate: derruba o químico e leva a dose."),
    C("Químico de Campo", 2, "Artilharia", "PRE", 0, 1, 2, 3,
      [("Lênicos", "E"), ("Medicina", "E"), ("Sobrevivência", "A"), ("Malandragem", "A"),
       ("Furtividade", "A"), ("Guerra", "A")],
      [A("Besta de Mão"), A("Adaga")],
      INV(tesouros=["Bracelete Elemental", "Foco da Intensificação"], consumiveis=["Poção da Nutrição"] * 2, ouro=10, tier=2),
      mod="Competente", org="[[Panvel]]", bairros=["[[Jardim Itu]]", "[[Delta Radioativo]]"],
      habilidades=["Tiro de Cobertura"], tipagem="AB+", linha_magia="Anima", elemento="Água",
      descricao="Joga química de área. O dano é o menor problema: o que fica no chão continua queimando."),
    C("Escolta de Comboio", 2, "Batedor", "AGI", 2, 3, 1, 0,
      [("Atletismo", "E"), ("Acrobacia", "E"), ("Guerra", "A"), ("Sobrevivência", "A"), ("Malandragem", "A")],
      [A("Alabarda", "Arma Obra-prima", 2), A("Espada Curva", "Imbuição da Ventania", 2)],
      INV(armadura="Armadura Leve", tesouros=["Cinto dos Ermos"],
          consumiveis=["Poção da Velocidade"], ouro=8, tier=2),
      mod="Competente", org="[[Zaffari]]", bairros=["[[Praia de Belas]]", "[[Nova Sarandi]]", "[[Lago Guaíba]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="O−",
      descricao="Protege carga em movimento. A luta dele é sempre em cima de algo que anda."),
]

CRIATURAS += [
    # ─────────────────────────── Facções ───────────────────────────
    C("Cobrador de Ponto", 0, "Soldado", "FOR", 3, 1, 1, 1,
      [("Intimidação", "A"), ("Sociedades", "A"), ("Malandragem", "A"), ("Atletismo", "A")],
      [A("Manopla")], INV(tier=0), org="[[Aliança dos Fundadores]]", bairros=["[[Centro Histórico]]"],
      tipagem="A−", descricao="Passa na banca toda sexta. Educado até a terceira semana sem pagamento."),
    C("Velho da Família", 2, "Líder", "PRE", 1, 0, 2, 3,
      [("Sociedades", "E"), ("Diplomacia", "E"), ("Enganação", "A"), ("Intimidação", "A"),
       ("Malandragem", "A"), ("Medicina", "A")],
      [A("Punhal", "Arma Obra-prima", 2)],
      INV(tesouros=["Colar da Eloquência"], consumiveis=["Poção de Cura"], ouro=15, tier=2),
      mod="Competente", org="[[Aliança dos Fundadores]]", bairros=["[[Centro Histórico]]"],
      habilidades=["Ordem de Ataque", "Não Recuem"], tipagem="A−",
      descricao="Manda sem levantar a voz, do fundo do Mercado Público. Quem encosta nele encosta em três bairros."),
    C("Passador de Dose", 0, "Encantador", "INT", 0, 1, 3, 2,
      [("Medicina", "A"), ("Malandragem", "A"), ("Enganação", "A"), ("Trônicos", "A"),
       ("Sociedades", "A"), ("Diplomacia", "A")],
      [A("Adaga")], INV(consumiveis=["Poção de Cura", "Poção da Coragem"], tier=0),
      org="[[Cartéis de Selênicos]]", bairros=["[[Restinga]]", "[[Cidade Baixa]]", "[[Quarto Distrito]]"],
      habilidades=["Dose no Braço"], tipagem="B−", linha_magia="Arcana Branca",
      descricao="Não briga: injeta. O capanga ao lado dele levanta de novo."),
    C("Mula do Cartel", 0, "Batedor", "AGI", 1, 3, 0, 2,
      [("Furtividade", "A"), ("Acrobacia", "A"), ("Malandragem", "A")],
      [A("Adaga de Duelo")], INV(consumiveis=["Poção da Velocidade"] * 2, tier=0),
      org="[[Cartéis de Selênicos]]", bairros=["[[Delta Radioativo]]", "[[Cidade Baixa]]", "[[Restinga]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="O−",
      descricao="Corre com a carga na cintura. Luta só o suficiente pra sumir na esquina."),
    C("Braço Armado do Cartel", 2, "Soldado", "FOR", 3, 1, 1, 1,
      [("Intimidação", "E"), ("Atletismo", "E"), ("Guerra", "A"), ("Malandragem", "A"), ("Sobrevivência", "A")],
      [A("Espada Curva", "Arma Obra-prima", 2), A("Manopla")],
      INV(armadura="Armadura Leve", consumiveis=["Poção da Coragem"], ouro=12, tier=2),
      mod="Elite", org="[[Cartéis de Selênicos]]", bairros=["[[Jardim Itu]]", "[[Praia de Belas]]"],
      habilidades=["Restringir Movimento", "Casco"], tipagem="O−",
      descricao="A escolta da carga grande. Nenhuma vontade de conversar."),
    C("Barão do Cartel", 3, "Líder", "PRE", 1, 0, 2, 3,
      [("Sociedades", "M"), ("Intimidação", "M"), ("Enganação", "E"), ("Diplomacia", "E"),
       ("Malandragem", "A"), ("Medicina", "A")],
      [A("Pistola Arcanônica"), A("Punhal", "Arma Obra-prima", 3)],
      INV(armadura="Armadura Leve", tesouros=["Colar da Eloquência"],
          consumiveis=["Poção de Cura"], ouro=60, tier=3),
      mod="Solo", org="[[Cartéis de Selênicos]]", bairros=["[[Jardim Itu]]", "[[Restinga]]"],
      habilidades=["Ordem de Ataque", "Não Recuem"], tipagem="AB−",
      descricao="O dono da rota. A garrucha dele é prova de que o Estado é sócio."),
    C("Barqueiro Armado", 0, "Batedor", "AGI", 2, 3, 0, 1,
      [("Atletismo", "A"), ("Sobrevivência", "A"), ("Malandragem", "A")],
      [A("Lança")], INV(tier=0), org="[[Aliança Livre das Palafitas]]",
      bairros=["[[Cidade Baixa]]", "[[Lago Guaíba]]"], habilidades=["Pelo Telhado"], tipagem="B−",
      descricao="Leva, cobra e às vezes entrega o passageiro. Luta em cima d'água, onde ele não cai e tu cai."),
    C("Atirador de Palafita", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Lênicos", "A"), ("Atletismo", "A"), ("Malandragem", "A")],
      [A("Besta Pesada", "Imbuição Hidratante", 1), A("Adaga")],
      INV(consumiveis=["Poção de Cura"], ouro=1, tier=1),
      mod="Competente", org="[[Aliança Livre das Palafitas]]", bairros=["[[Cidade Baixa]]"],
      habilidades=["Tiro de Cobertura"], tipagem="AB+", linha_magia="Anima", elemento="Água",
      descricao="Atira de cima da tábua e recua pelo varal. A passarela é a defesa dele."),
    C("Catador Armado", 0, "Batedor", "AGI", 2, 3, 0, 1,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Malandragem", "A")],
      [A("Azagaia"), A("Arco Curto")], INV(tier=0), org="[[Sindicato dos Catadores]]",
      bairros=["[[Zona Deserta]]", "[[Restinga]]", "[[Centro Histórico]]"],
      habilidades=["Oportunista"], tipagem="O−",
      descricao="O olheiro do ferro-velho. Sabe qual pilha esconde o quê — e quem passou por ali."),
    C("Ferro-Velho", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sobrevivência", "A"), ("Guerra", "A")],
      [A("Malho", "Imbuição Explosiva", 1)],
      INV(tesouros=["Pulseira da Potência"], ouro=1, tier=1),
      mod="Competente", org="[[Clã da Ferrugem]]", bairros=["[[Zona Deserta]]", "[[Restinga]]", "[[Petrópolis]]"],
      habilidades=["Vigor Bruto"], tipagem="A−",
      descricao="Prótese de sucata e marreta. Bate igual à máquina de onde tirou o braço."),
    C("Mestre de Sucata", 2, "Líder", "PRE", 1, 0, 2, 3,
      [("Sobrevivência", "E"), ("Sociedades", "E"), ("Intimidação", "A"), ("Malandragem", "A"),
       ("Medicina", "A"), ("Guerra", "A")],
      [A("Maça"), A("Azagaia", "Imbuição Relampejante", 2)],
      INV(armadura="Armadura Leve", tesouros=["Cinto dos Ermos"],
          consumiveis=["Poção de Cura"], ouro=10, tier=2),
      mod="Competente", org="[[Clã da Ferrugem]]", bairros=["[[Zona Deserta]]", "[[Restinga]]"],
      habilidades=["Ordem de Ataque", "Apito"], tipagem="B−",
      descricao="Manda no ferro e no gato de luz de meia cidade. Negocia antes de brigar — e ganha nos dois."),
    C("Leão de Chácara", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Intimidação", "A"), ("Atletismo", "A"), ("Sociedades", "A"), ("Acrobacia", "A")],
      [A("Manopla")], INV(tesouros=["Anel da Resistência"], armadura="Armadura Leve", consumiveis=["Poção da Coragem"], ouro=1, tier=1),
      mod="Competente", org="[[Ordem dos Subsolos]]", bairros=["[[Quarto Distrito]]", "[[Bom Fim]]"],
      habilidades=["Bruto Aterrorizador", "Parede de Escudo"], tipagem="O−",
      descricao="Segura a porta do Teatro Quarto Distrito. O corredor é estreito de propósito."),
    C("Agulha da Ordem", 2, "Assassino", "AGI", 2, 3, 1, 0,
      [("Furtividade", "E"), ("Malandragem", "E"), ("Acrobacia", "A"), ("Enganação", "A"), ("Sociedades", "A")],
      [A("Punhal", "Imbuição Torrencial", 2), A("Adaga")],
      INV(tesouros=["Capa Discreta"], consumiveis=["Poção da Velocidade"] * 2, ouro=9, tier=2),
      mod="Competente", org="[[Ordem dos Subsolos]]", bairros=["[[Quarto Distrito]]"],
      habilidades=["Alvo de Assassinato", "Pelo Telhado"], tipagem="A−",
      descricao="Mata no meio da festa e sai dançando. Ninguém vê, ninguém fala."),
    C("Estivador de Confiança", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sobrevivência", "A"), ("Malandragem", "A"), ("Sociedades", "A")],
      [A("Maça Estrela"), A("Alabarda")],
      INV(armadura="Armadura Leve", ouro=1, tier=1),
      org="[[Consórcio das Bandeiras]]", bairros=["[[Praia de Belas]]", "[[Lago Guaíba]]"],
      tipagem="O−", descricao="Briga de gancho e corrente no cais. Conhece cada contêiner do Porto Novo."),
    C("Chefe de Armazém", 2, "Líder", "PRE", 2, 0, 1, 3,
      [("Sociedades", "E"), ("Intimidação", "E"), ("Malandragem", "A"), ("Guerra", "A"), ("Diplomacia", "A")],
      [A("Alfange", "Arma Obra-prima", 2)],
      INV(armadura="Armadura Leve", tesouros=["Colar da Eloquência"],
          consumiveis=["Poção de Cura"], ouro=12, tier=2),
      mod="Competente", org="[[Consórcio das Bandeiras]]", bairros=["[[Praia de Belas]]"],
      habilidades=["Ordem de Ataque", "Apito"], tipagem="A−",
      descricao="Comanda a descarga — e a emboscada que espera do outro lado dela."),
    C("Segurança do Cartel dos Eixos", 0, "Soldado", "FOR", 3, 2, 1, 0,
      [("Atletismo", "A"), ("Malandragem", "A"), ("Sobrevivência", "A"), ("Intimidação", "A")],
      [A("Azagaia"), A("Porrete")], INV(tier=0),
      org="[[Cartel dos Eixos]]", bairros=["[[Passo D'Areia]]"], tipagem="B−",
      descricao="Chapa de oficina que não quer conversa: a ferramenta na mão dele já é arma."),
    C("Piloto de Racha", 1, "Batedor", "AGI", 1, 3, 1, 1,
      [("Acrobacia", "A"), ("Atletismo", "A"), ("Malandragem", "A"), ("Sobrevivência", "A"), ("Sociedades", "A")],
      [A("Adaga de Duelo")],
      INV(tesouros=["Botas Fluídicas"], consumiveis=["Poção da Velocidade"], ouro=2, tier=1),
      mod="Competente", org="[[Cartel dos Eixos]]", bairros=["[[Passo D'Areia]]", "[[Nova Sarandi]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="O−",
      descricao="Entra e sai da cena. Metade da briga acontece em movimento."),
    C("Instalador Pirata", 1, "Encantador", "INT", 0, 1, 3, 2,
      [("Trônicos", "A"), ("Medicina", "A"), ("Malandragem", "A"), ("Sociedades", "A"),
       ("Enganação", "A"), ("Diplomacia", "A"), ("Acrobacia", "A")],
      [A("Adaga", "Imbuição Incendiária", 1)],
      INV(tesouros=["Luva do Arcanista", "Ferramenta Obra-prima"], consumiveis=["Poção da Coragem"], ouro=3, tier=1),
      mod="Competente", org="[[Círculo das Ligas]]", bairros=["[[Petrópolis]]", "[[Quarto Distrito]]"],
      habilidades=["Dose no Braço"], tipagem="AB−", linha_magia="Arcana Branca",
      descricao="Liga módulo no capanga no meio da luta. Sem garantia: às vezes o capanga é que apaga."),
    C("Capanga de Oficina", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Guerra", "A"), ("Sobrevivência", "A")],
      [A("Picareta de Guerra")], INV(armadura="Armadura Leve", ouro=1, tier=1),
      org="[[Círculo das Ligas]]", bairros=["[[Petrópolis]]"],
      habilidades=["Vigor Bruto"], tipagem="A−",
      descricao="Protege a bancada com o que estava em cima dela."),
    C("Refinador", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Lênicos", "A"), ("Medicina", "A"), ("Sobrevivência", "A"), ("Malandragem", "A"), ("Atletismo", "A")],
      [A("Besta Leve"), A("Alfange")],
      INV(tesouros=["Bracelete Elemental", "Foco da Consistência"], consumiveis=["Poção da Nutrição"] * 2, ouro=2, tier=1),
      org="[[Comando Itu-Química]]", bairros=["[[Jardim Itu]]"],
      habilidades=["Tiro de Cobertura"], tipagem="O+", linha_magia="Anima", elemento="Fogo",
      descricao="Frasco, vapor e queimadura. Luta como quem despeja, não como quem golpeia."),
    C("Guarda de Refino", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Guerra", "A"), ("Intimidação", "A"), ("Sobrevivência", "A"), ("Medicina", "A")],
      [A("Espada Longa", "Imbuição Congelante", 1)], INV(armadura="Armadura Leve", consumiveis=["Poção da Nutrição"], ouro=1, tier=1),
      mod="Competente", org="[[Comando Itu-Química]]", bairros=["[[Jardim Itu]]"],
      habilidades=["Restringir Movimento"], tipagem="B−",
      descricao="Tropa de fábrica tomada. Turno de doze horas e nenhum sindicato."),
    C("Biopirata", 1, "Batedor", "AGI", 1, 3, 1, 1,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Acrobacia", "A"), ("Medicina", "A"), ("Lênicos", "A")],
      [A("Arco de Caça"), A("Machadinha"), A("Adaga")],
      INV(tesouros=["Cinto dos Ermos"], consumiveis=["Poção da Velocidade"], ouro=2, tier=1),
      org="[[Liga da Estufa]]", bairros=["[[Jardim Botânico]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="A−",
      descricao="Furta semente da Estufa Histórica e some pelo mato antes do alarme."),
    C("Envenenador", 2, "Supressor", "INT", 0, 1, 3, 2,
      [("Medicina", "E"), ("Lênicos", "E"), ("Furtividade", "A"), ("Sobrevivência", "A"),
       ("Malandragem", "A"), ("Trônicos", "A"), ("Enganação", "A")],
      [A("Besta de Mão", "Imbuição Enraizante", 2), A("Punhal")],
      INV(tesouros=["Luvas Purificadas"], consumiveis=["Poção da Nutrição"] * 2, ouro=9, tier=2),
      mod="Competente", org="[[Liga da Estufa]]", bairros=["[[Jardim Botânico]]", "[[Moinhos de Vento]]"],
      habilidades=["Restringir Movimento", "Queimar a Rota"], tipagem="B−", linha_magia="Arcana Negra",
      descricao="Tira o herói da luta sem matar. O grupo perde alguém por três rodadas — e o resto vira número."),
    C("Escolta Particular", 2, "Assassino", "AGI", 2, 3, 1, 0,
      [("Acrobacia", "E"), ("Sociedades", "E"), ("Furtividade", "A"), ("Diplomacia", "A"), ("Enganação", "A")],
      [A("Rapieira", "Arma Obra-prima", 2), A("Punhal")],
      INV(tesouros=["Anel do Equilíbrio"], consumiveis=["Poção de Cura"], ouro=14, tier=2),
      mod="Competente", org="[[Sociedade dos Jardins]]", bairros=["[[Moinhos de Vento]]", "[[Ipanema]]"],
      habilidades=["Alvo de Assassinato"], tipagem="A−",
      descricao="Esgrima de clube e terno de alfaiate. Atira primeiro por educação."),
    C("Corretor de Chantagem", 2, "Encantador", "INT", 0, 1, 3, 2,
      [("Sociedades", "E"), ("Enganação", "E"), ("Diplomacia", "A"), ("Trônicos", "A"),
       ("Malandragem", "A"), ("Medicina", "A"), ("Acrobacia", "A")],
      [A("Punhal")], INV(tesouros=["Colar da Eloquência"], consumiveis=["Poção da Coragem"], ouro=20, tier=2),
      mod="Competente", org="[[Sociedade dos Jardins]]", bairros=["[[Moinhos de Vento]]"],
      habilidades=["Dose no Braço"], tipagem="AB−", linha_magia="Arcana Branca",
      descricao="A arma dele é o dossiê. Vira aliado do grupo contra o grupo."),
    C("Miliciano da Estrada", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Sobrevivência", "A"), ("Guerra", "A"), ("Intimidação", "A"), ("Atletismo", "A"), ("Sociedades", "A")],
      [A("Espada Curva", "Imbuição Ciclonal", 1)], INV(armadura="Armadura Leve", ouro=2, tier=1),
      mod="Competente", org="[[Movimento Restinga Livre]]", bairros=["[[Restinga]]"], tipagem="O−",
      descricao="A guarita da estrada única. Decide quem entra — em dólar."),
    C("Guarita da Restinga", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Furtividade", "A"), ("Sobrevivência", "A"), ("Lênicos", "A"), ("Guerra", "A"), ("Atletismo", "A")],
      [A("Arco de Guerra"), A("Funda"), A("Espada Curva")],
      INV(tesouros=["Amplificador Audiovisual"], ouro=1, tier=1),
      org="[[Movimento Restinga Livre]]", bairros=["[[Restinga]]"],
      habilidades=["Tiro de Cobertura"], tipagem="A+", linha_magia="Anima", elemento="Terra",
      descricao="Fogo de cobertura da Torre de Vigilância Caseira. Improvisa munição com o que o mercado tem."),
    C("Ex-Praça", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Guerra", "A"), ("Atletismo", "A"), ("Intimidação", "A"), ("Sobrevivência", "A"), ("Medicina", "A")],
      [A("Espada Curta"), A("Porrete")],
      INV(armadura="Armadura Leve", consumiveis=["Poção de Cura"], ouro=2, tier=1),
      mod="Competente", org="[[Consórcio Paraguassu]]", bairros=["[[Costa e Silva]]"],
      habilidades=["Restringir Movimento", "Parede de Escudo"], tipagem="A−",
      descricao="Treinamento de quartel, moral de milícia. Sabe exatamente o que a Brigada vai fazer."),
    C("Miliciano Veterano", 2, "Bruto", "FOR", 3, 2, 0, 1,
      [("Guerra", "E"), ("Intimidação", "E"), ("Atletismo", "A"), ("Sobrevivência", "A")],
      [A("Machado de Batalha", "Arma Obra-prima", 2)],
      INV(armadura="Armadura Leve", tesouros=["Diadema da Ameaça"],
          consumiveis=["Poção da Coragem"], ouro=8, tier=2),
      mod="Competente", org="[[Consórcio Paraguassu]]", bairros=["[[Costa e Silva]]", "[[Zona Deserta]]"],
      habilidades=["Bruto Aterrorizador", "Casco"], tipagem="O−",
      descricao="O que sobrou da tropa, pior e mais livre. Não tem regulamento pra segurar."),
    C("Segurança de Condomínio", 1, "Soldado", "FOR", 3, 1, 1, 1,
      [("Sociedades", "A"), ("Intimidação", "A"), ("Atletismo", "A"), ("Guerra", "A"), ("Diplomacia", "A")],
      [A("Porrete")], INV(armadura="Armadura Leve", escudo=("Broquel", "Broquel Obra-prima"), ouro=2, tier=1),
      mod="Competente", org="[[Clube dos Sete Portos]]", bairros=["[[Ipanema]]", "[[Moinhos de Vento]]"],
      habilidades=["Parede de Escudo"], tipagem="A−",
      descricao="Barra na guarita e atira do muro. Educadíssimo com quem tem sobrenome."),
    C("Chefe de Segurança", 2, "Líder", "PRE", 2, 0, 1, 3,
      [("Sociedades", "E"), ("Guerra", "E"), ("Diplomacia", "A"), ("Intimidação", "A"), ("Enganação", "A")],
      [A("Pistola Arcanônica"), A("Espada Curta", "Arma Obra-prima", 2)],
      INV(armadura="Armadura Leve", tesouros=["Anel Mensageiro"],
          consumiveis=["Poção de Cura"], ouro=18, tier=2),
      mod="Competente", org="[[Clube dos Sete Portos]]", bairros=["[[Ipanema]]"],
      habilidades=["Ordem de Ataque", "Fechar Formação"], tipagem="O−",
      descricao="Coordena as escoltas pelo rádio — e some quando a coisa aperta."),
    C("Saqueador de Vagão", 1, "Batedor", "AGI", 2, 3, 1, 0,
      [("Atletismo", "A"), ("Acrobacia", "A"), ("Malandragem", "A"), ("Sobrevivência", "A"), ("Guerra", "A")],
      [A("Tacape"), A("Adaga de Duelo")],
      INV(tesouros=["Braceletes de Pedra"], ouro=1, tier=1),
      org="[[Confraria dos Trilhos]]", bairros=["[[Nova Sarandi]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="B−",
      descricao="Ataca em movimento na Ferroviária Nacional: sobe, leva e pula."),
    C("Boêmio Armado", 0, "Batedor", "AGI", 1, 3, 1, 1,
      [("Malandragem", "A"), ("Acrobacia", "A"), ("Sociedades", "A"), ("Enganação", "A")],
      [A("Adaga")], INV(tier=0), org="[[Irmandade do Café Preto]]", bairros=["[[Bom Fim]]"],
      tipagem="AB−", descricao="Briga de bar do Bar Ocidente que vira perseguição por três quarteirões."),
    C("Representante da Camisa 12", 0, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sociedades", "A")],
      [A("Bordão"), A("Manopla")], INV(tier=0),
      org="[[Camisa 12]]", bairros=["[[Praia de Belas]]", "[[Jardim Botânico]]"], tipagem="O−",
      descricao="Vem em bando. Sozinho não é nada — e é por isso que nunca vem sozinho."),
    C("Cabeça de Torcida", 1, "Líder", "PRE", 2, 0, 1, 3,
      [("Intimidação", "A"), ("Sociedades", "A"), ("Atletismo", "A"), ("Malandragem", "A"), ("Diplomacia", "A")],
      [A("Maça Estrela")], INV(armadura="Armadura Leve", tesouros=["Diadema da Ameaça"], ouro=4, tier=1),
      org="[[Camisa 12]]", bairros=["[[Praia de Belas]]", "[[Jardim Botânico]]"],
      habilidades=["Apito", "Não Recuem"], tipagem="O−",
      descricao="Transforma o bando em problema: quem ele aponta, trinta perseguem."),
    C("Piquete", 0, "Bruto", "FOR", 3, 1, 1, 1,
      [("Atletismo", "A"), ("Intimidação", "A"), ("Sociedades", "A"), ("Guerra", "A")],
      [A("Azagaia"), A("Pique")], INV(tier=0), org="[[Sindicato dos Metalúrgicos]]",
      bairros=["[[Petrópolis]]", "[[Nova Sarandi]]"], habilidades=["Parede de Escudo"], tipagem="A−",
      descricao="Barra a Rua das Indústrias na greve. Não quer machucar — mas ninguém passa."),
    C("Sabotador", 1, "Supressor", "INT", 0, 2, 3, 1,
      [("Trônicos", "A"), ("Malandragem", "A"), ("Furtividade", "A"), ("Sociedades", "A"),
       ("Enganação", "A"), ("Acrobacia", "A"), ("Medicina", "A")],
      [A("Adaga de Duelo")], INV(tesouros=["Luvas do Ladrão"], consumiveis=["Poção da Coragem"], ouro=1, tier=1),
      org="[[Resistência Urbana Gaúcha]]", bairros=["[[Bom Fim]]", "[[Quarto Distrito]]", "[[Centro Histórico]]"],
      habilidades=["Restringir Movimento", "Queimar a Rota"], tipagem="B−", linha_magia="Arcana Negra",
      descricao="Apaga a luz e o sinal. Costuma ser aliado — até o grupo aceitar serviço da firma errada."),
    C("Agulha de Beco", 0, "Assassino", "AGI", 1, 3, 1, 1,
      [("Furtividade", "A"), ("Malandragem", "A"), ("Acrobacia", "A"), ("Enganação", "A")],
      [A("Punhal"), A("Pontos de Pressão")], INV(tier=0), org="", bairros=["[[Restinga]]", "[[Cidade Baixa]]", "[[Quarto Distrito]]"],
      habilidades=["Alvo de Assassinato"], tipagem="O−",
      descricao="O punguista que vira faca quando é pego."),
    C("Chefe de Esquina", 0, "Líder", "PRE", 2, 0, 1, 3,
      [("Intimidação", "A"), ("Sociedades", "A"), ("Malandragem", "A"), ("Enganação", "A")],
      [A("Manopla")], INV(ouro=1, tier=0), org="",
      bairros=["[[Restinga]]", "[[Cidade Baixa]]", "[[Quarto Distrito]]", "[[Jardim Itu]]"],
      habilidades=["Apito"], tipagem="B−",
      descricao="O primeiro 'chefe' que o grupo enfrenta, em qualquer bairro pobre. Manda em seis."),
    C("O Despachante", 3, "Assassino", "AGI", 2, 3, 1, 0,
      [("Furtividade", "M"), ("Malandragem", "M"), ("Acrobacia", "E"), ("Sociedades", "E"), ("Enganação", "A")],
      [A("Espada Bastarda", "Imbuição de Aço Solar", 3), A("Punhal")],
      INV(armadura="Armadura Leve", tesouros=["Capa Discreta"],
          consumiveis=["Poção da Velocidade"] * 2, ouro=50, tier=3),
      mod="Solo", org="[[A Caixinha]]", bairros=["[[Porto Alegre]]"],
      habilidades=["Alvo de Assassinato", "Oportunista", "Pelo Telhado"], tipagem="A−",
      descricao="Quem cobra a conta de quem trai a Caixinha. Nenhum registro em lugar nenhum."),
]

CRIATURAS += [
    # ─────────────────────────── Não-gente ───────────────────────────
    C("Rato-do-Delta", 0, "Batedor", "AGI", 1, 3, 0, 2,
      [("Furtividade", "A"), ("Acrobacia", "A"), ("Sobrevivência", "A")],
      [A("Presas de Lobo"), A("Garras")], INV(tier=0), org="[[Delta Radioativo]]", bairros=["[[Delta Radioativo]]", "[[Cidade Baixa]]"],
      habilidades=["Oportunista"], tipagem="—", raca=INCOMUM, tamanho="Pequeno",
      descricao="Vem em dezenas pela Rua do Rato. Cada um é troco; o problema é a quantidade."),
    C("Cão Mutante", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Sobrevivência", "A"), ("Furtividade", "A"), ("Intimidação", "A")],
      [A("Garra de Tigre"), A("Mandíbula")], INV(tier=1), org="[[Delta Radioativo]]", bairros=["[[Delta Radioativo]]", "[[Zona Deserta]]"],
      habilidades=["Bruto Aterrorizador"], tipagem="—", raca=INCOMUM,
      descricao="Investe e derruba. A pele descascada não é ferida: é o que a chuva ácida fez."),
    C("Coisa da Lagoa", 2, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "E"), ("Sobrevivência", "E"), ("Intimidação", "A"), ("Furtividade", "A")],
      [A("Cauda"), A("Garras Grandes"), A("Mandíbula Enorme")], INV(ouro=25, tier=2),
      mod="Solo", org="[[Lagoa do Pinheiro]]", bairros=["[[Delta Radioativo]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Grande",
      descricao="O que o depósito tóxico a céu aberto fez com algo que já foi bicho."),
    C("Colônia Mutante", 3, "Supressor", "INT", 1, 0, 3, 2,
      [("Sobrevivência", "M"), ("Furtividade", "M"), ("Lênicos", "E"), ("Atletismo", "E"),
       ("Medicina", "A"), ("Acrobacia", "A"), ("Trônicos", "A")],
      [A("Cauda Colossal"), A("Mandíbula Colossal")], INV(ouro=30, tier=3),
      mod="Solo", org="[[Delta Radioativo]]", bairros=["[[Delta Radioativo]]"],
      habilidades=["Restringir Movimento", "Queimar a Rota", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Enorme", linha_magia="Arcana Negra",
      descricao="Não é um bicho: é a estação inteira. O chão prende, o ar consome."),
    C("Drone de Guarda", 1, "Artilharia", "PRE", 0, 2, 1, 3,
      [("Trônicos", "A"), ("Furtividade", "A"), ("Guerra", "A"), ("Acrobacia", "A"), ("Lênicos", "A")],
      [A("Besta")], INV(tesouros=["Sensor Arcano"], tier=1),
      org="[[Complexo de Testes Orion]]", bairros=["[[Zona Deserta]]"],
      habilidades=["Tiro de Cobertura"], tipagem="A+", linha_magia="Anima", elemento="Terra",
      raca=INCOMUM, tamanho="Pequeno",
      descricao="Torre voadora com dardo. Sobe fora de alcance, atira e volta."),
    C("Drone Sequestrado", 1, "Batedor", "AGI", 0, 3, 2, 1,
      [("Acrobacia", "A"), ("Furtividade", "A"), ("Trônicos", "A"), ("Guerra", "A"),
       ("Malandragem", "A"), ("Sociedades", "A")],
      [A("Besta de Mão")], INV(tesouros=["Anel Mensageiro"], tier=1),
      org="[[Base Fantasma]]", bairros=["[[Zona Deserta]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="—", raca=INCOMUM, tamanho="Pequeno",
      descricao="Responde a quem gritar mais alto no rádio. Vira contra quem o chamou."),
    C("Androide de Vigilância", 2, "Soldado", "FOR", 3, 1, 2, 0,
      [("Guerra", "E"), ("Furtividade", "E"), ("Atletismo", "A"), ("Trônicos", "A"),
       ("Acrobacia", "A"), ("Sociedades", "A")],
      [A("Espada Curta", "Arma Obra-prima", 2)],
      INV(armadura="Armadura Pesada", tesouros=["Amplificador Audiovisual"], ouro=40, tier=2),
      mod="Elite", org="[[Complexo de Testes Orion]]", bairros=["[[Zona Deserta]]", "[[Delta Radioativo]]"],
      habilidades=["Restringir Movimento", "Casco"], tipagem="—", raca=INCOMUM,
      descricao="Continua cumprindo uma ordem que ninguém lembra de ter dado."),
    C("Protótipo Orion", 3, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "M"), ("Intimidação", "M"), ("Guerra", "E"), ("Acrobacia", "E")],
      [A("Cauda Colossal"), A("Garras Colossais")],
      INV(armadura=("Armadura Pesada", "Armadura Obra-prima"), tier=3),
      mod="Solo", org="[[Complexo de Testes Orion]]", bairros=["[[Zona Deserta]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Enorme",
      descricao="O chefão do fim da linha, no subsolo da Zona Deserta. Foi feito pra não ser desligado."),
    C("Corredor Fantasma", 3, "Batedor", "AGI", 1, 3, 2, 0,
      [("Acrobacia", "M"), ("Furtividade", "M"), ("Atletismo", "E"), ("Trônicos", "E"),
       ("Guerra", "A"), ("Malandragem", "A")],
      [A("Garra de Tigre"), A("Garras Afiadas")], INV(tesouros=["Botas Fluídicas"], tier=3),
      mod="Solo", org="[[Base Fantasma]]", bairros=["[[Zona Deserta]]", "[[Delta Radioativo]]"],
      habilidades=["Oportunista", "Pelo Telhado"], tipagem="—", raca=INCOMUM,
      descricao="Rápido demais pra cercar. Some do sinal e reaparece atrás da fila."),
    C("Bateria da Torre", 3, "Artilharia", "PRE", 0, 1, 2, 3,
      [("Guerra", "M"), ("Lênicos", "M"), ("Furtividade", "E"), ("Trônicos", "E"),
       ("Atletismo", "A"), ("Acrobacia", "A")],
      [A("Besta", "Imbuição Enraizante", 3)], INV(tesouros=["Bracelete Elemental", "Foco da Penetração"], tier=3),
      mod="Elite", org="[[Embratel]]", bairros=["[[Costa e Silva]]", "[[Moinhos de Vento]]"],
      habilidades=["Tiro de Cobertura"], tipagem="B+", linha_magia="Anima", elemento="Vento",
      raca=INCOMUM, tamanho="Grande",
      descricao="A torre de escuta que também atira. Cobre o bairro inteiro e nunca está onde o grupo está."),
]

# ── Bicharada do Delta, da Restinga e da Zona Deserta ────────────────────────
# Pedido do mestre (2026-09-12): o bestiário tem que exercitar o SISTEMA
# inteiro — pelo menos uma criatura por arma do catálogo. As armas naturais
# (chifre, presa, mandíbula, cauda, garra) só existem em bicho, e a POA tem
# onde: o que a enchente soltou, o que a chuva ácida mudou e o que fugiu do
# pasto quando o pasto morreu. Arma natural NÃO hospeda módulo (nenhum
# `AplicavelA` cita o grupo), então nenhuma delas tem propriedade.
CRIATURAS += [
    C("Bode da Restinga", 0, "Batedor", "AGI", 2, 3, 0, 1,
      [("Atletismo", "A"), ("Sobrevivência", "A"), ("Acrobacia", "A")],
      [A("Chifres"), A("Presas")], INV(tier=0),
      org="[[Restinga]]", bairros=["[[Restinga]]", "[[Zona Deserta]]"],
      habilidades=["Oportunista"], tipagem="—", raca=INCOMUM,
      descricao="Bode de solta que ninguém reclama. Investe de lado, no escuro, e some no mato antes de alguém decidir atirar."),
    C("Capivara Blindada", 1, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "A"), ("Sobrevivência", "A"), ("Furtividade", "A"), ("Intimidação", "A")],
      [A("Mandíbula Grande"), A("Presas Grandes")], INV(tier=1),
      org="[[Delta Radioativo]]", bairros=["[[Delta Radioativo]]", "[[Cidade Baixa]]"],
      habilidades=["Casco", "Vigor Bruto"], tipagem="—", raca=INCOMUM, tamanho="Grande",
      descricao="A capivara do arroio saiu do arroio. A placa de couro endureceu junto com o resto e ela não corre mais de ninguém."),
    C("Cascavel do Cais", 1, "Assassino", "AGI", 1, 3, 0, 2,
      [("Furtividade", "A"), ("Acrobacia", "A"), ("Sobrevivência", "A"), ("Atletismo", "A")],
      [A("Presas Letais"), A("Cauda Grande")], INV(tier=1),
      org="[[Quarto Distrito]]", bairros=["[[Quarto Distrito]]", "[[Cidade Baixa]]"],
      habilidades=["Alvo de Assassinato", "Oportunista"], tipagem="—", raca=INCOMUM,
      descricao="Mora no vão do cais e cobra pedágio de quem mexe na carga. O guizo é o único aviso que ela dá."),
    C("Carneiro do Morro", 1, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "A"), ("Sobrevivência", "A"), ("Acrobacia", "A"), ("Intimidação", "A")],
      [A("Chifres Letais")], INV(tier=1),
      org="[[Restinga]]", bairros=["[[Restinga]]", "[[Zona Deserta]]"],
      habilidades=["Bruto Aterrorizador"], tipagem="—", raca=INCOMUM,
      descricao="Carneiro de rebanho perdido, chifre torto de tanto bater em portão. Abre a porta antes do dono."),
    C("Javali da Restinga", 2, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "E"), ("Sobrevivência", "E"), ("Furtividade", "A"), ("Intimidação", "A")],
      [A("Presas Enormes"), A("Chifres Enormes")], INV(tier=2),
      mod="Competente", org="[[Restinga]]",
      bairros=["[[Restinga]]", "[[Zona Deserta]]", "[[Delta Radioativo]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto"], tipagem="—", raca=INCOMUM, tamanho="Grande",
      descricao="O javali que a enchente soltou virou dono da mata seca. Atravessa cerca como se cerca não existisse."),
    C("Touro do Pasto Morto", 2, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "E"), ("Intimidação", "E"), ("Sobrevivência", "A"), ("Acrobacia", "A")],
      [A("Chifres Grandes"), A("Cauda Pesada")], INV(tier=2),
      mod="Elite", org="[[Aliança dos Fundadores]]",
      bairros=["[[Zona Deserta]]", "[[Costa e Silva]]"],
      habilidades=["Bruto Aterrorizador", "Casco"], tipagem="—", raca=INCOMUM, tamanho="Grande",
      descricao="Escapou do pasto da Aliança quando o pasto morreu. Carrega marca de ferro na anca e nenhum dono."),
    C("Jacaré do Arroio", 2, "Bruto", "FOR", 3, 2, 0, 1,
      [("Atletismo", "E"), ("Furtividade", "E"), ("Sobrevivência", "A"), ("Intimidação", "A")],
      [A("Mandíbula Afiada"), A("Cauda Enorme")], INV(tier=2),
      org="[[Delta Radioativo]]", bairros=["[[Delta Radioativo]]", "[[Lago Guaíba]]"],
      habilidades=["Casco", "Oportunista"], tipagem="—", raca=INCOMUM, tamanho="Enorme",
      descricao="Fica de olho fora d'água na boca do arroio, parado o dia inteiro. Só se mexe quando vale a pena."),
    C("Onça do Jardim", 3, "Assassino", "AGI", 2, 3, 0, 1,
      [("Furtividade", "M"), ("Acrobacia", "M"), ("Atletismo", "E"), ("Sobrevivência", "E")],
      [A("Garras Enormes")], INV(tier=3),
      mod="Elite", org="[[Jardim Botânico]]",
      bairros=["[[Jardim Botânico]]", "[[Petrópolis]]"],
      habilidades=["Alvo de Assassinato", "Pelo Telhado", "Oportunista"], tipagem="—",
      raca=INCOMUM, tamanho="Grande",
      descricao="Saiu do zoológico quando o zoológico acabou. Come em cima do telhado e desce sem barulho nenhum."),
    C("A Mãe do Delta", 3, "Bruto", "FOR", 3, 1, 0, 2,
      [("Atletismo", "M"), ("Intimidação", "M"), ("Sobrevivência", "E"), ("Furtividade", "E")],
      [A("Cauda de Dragão"), A("Presas Colossais"), A("Chifres Colossais")],
      INV(ouro=40, tier=3),
      mod="Solo", org="[[Delta Radioativo]]", bairros=["[[Delta Radioativo]]"],
      habilidades=["Bruto Aterrorizador", "Vigor Bruto", "Casco"], tipagem="—",
      raca=INCOMUM, tamanho="Enorme",
      descricao="O que o Delta virou quando ninguém estava olhando. Tudo que mora ali nasceu dela ou foge dela."),
]


# ═══════════════════════════ ENCONTROS PRONTOS ═══════════════════════════
# Um encontro é (nome, tier, onde, situação, roster). O `alvo` é a dificuldade
# que ele DEVE dar pro grupo de referência do rank (4 heróis no nível médio da
# faixa: T0→2, T1→5, T2→8, T3→10) — o gerador confere, então "tier 2" não sai
# trivial pra quem está no nível 8. Velocidade por combatente já vem definida
# (super rápido · rápido · lento), que é o que o app usa na iniciativa.

def E(nome, tier, onde, situacao, roster, alvo="DIFICIL"):
    return {"nome": nome, "tier": tier, "onde": onde, "situacao": situacao,
            "roster": [{"qtd": q, "criatura": c, "velocidade": v} for q, c, v in roster],
            "alvo": alvo}


ENCONTROS = [
    E("A Coisa da Lagoa", 2, "[[Lagoa do Pinheiro]] · [[Delta Radioativo]]",
      "Chefe de bicho na beira: o grandão no meio e a bicharada do Delta fechando o cerco.",
      [(1, "Coisa da Lagoa", "lento"), (6, "Cão Mutante", "rápido"), (2, "Capivara Blindada", "lento"), (1, "Javali da Restinga", "rápido")],
      "LETAL"),
    E("A Conta da Caixinha", 3, "Genérico — o endereço onde o grupo dorme.",
      "Solo puro, sem apoio. Ele não quer vencer o grupo: quer um deles.",
      [(1, "O Despachante", "super rápido")],
      "FÁCIL"),
    E("A Coronel em Pessoa", 3, "[[Centro Histórico]] · [[Bom Fim]]",
      "Quando a Operação Silêncio vira pessoal. Ela assina, e agora aparece.",
      [(1, "Coronel Luciana Prado", "super rápido"), (2, "Cabo de Choque", "lento"), (1, "Franco-Atirador da Brigada", "rápido")],
      "DIFICIL"),
    E("Auditoria da Gradiente", 3, "[[Edifício Concorde]] · [[Moinhos de Vento]]",
      "O mais difícil da lista: quem manda não luta, e o prédio inteiro é arma dele.",
      [(1, "Sistemista da Gradiente", "lento"), (1, "Auditor de Campo", "rápido"), (2, "Escolta de Diretoria", "super rápido")],
      "LETAL"),
    E("Bancada do Círculo", 1, "[[Petrópolis]]",
      "O Encantador liga módulo nos capangas: a luta piora sozinha.",
      [(5, "Capanga de Oficina", "lento"), (2, "Instalador Pirata", "rápido")],
      "FÁCIL"),
    E("Batida Grande", 2, "Genérico — qualquer bairro, quando a Brigada decide fechar o quarteirão.",
      "A patrulha vira operação: o sargento faz os quatro valerem por oito.",
      [(2, "Sargento de Pelotão", "rápido"), (8, "Brigadiano de Esquina", "lento"), (3, "Guarda", "lento"), (2, "Cão de Brigada", "rápido")],
      "DIFICIL"),
    E("Batida do Quartel", 3, "[[Quartel-General do Exército]] · [[Costa e Silva]]",
      "Pólvora legal, comando de verdade e fogo indireto que não para de chegar.",
      [(2, "Pelotão de Guarnição", "lento"), (1, "Oficial de Operações", "super rápido"), (1, "Bateria da Torre", "lento")],
      "LETAL"),
    E("Blitz na Esquina", 0, "Genérico — qualquer calçada depois das 23h, no toque de recolher.",
      "O grupo carrega algo que não quer mostrar. É o primeiro combate de campanha: ensina que farda se resolve conversando, correndo ou pagando.",
      [(4, "Brigadiano de Esquina", "lento"), (1, "Cão de Brigada", "rápido")],
      "FÁCIL"),
    E("Boca Fechada", 0, "Genérico — beco de bairro pobre.",
      "O grupo pergunta demais sobre dose. Os capangas levantam de novo.",
      [(1, "Passador de Dose", "lento"), (6, "Agulha de Beco", "rápido")],
      "DIFICIL"),
    E("Cerco da Vila Militar", 1, "[[Vila Militar do Paraguassu]] · [[Costa e Silva]]",
      "Milícia com treino de quartel e uma guarita cobrindo a única saída.",
      [(7, "Ex-Praça", "lento"), (3, "Atirador de Torre", "lento")],
      "LETAL"),
    E("Cobrança na Banca", 0, "[[Centro Histórico]] · [[Palafitas do Mercado]]",
      "Briga com testemunha: bater na frente do mercado tem preço social.",
      [(4, "Cobrador de Ponto", "lento"), (1, "Chefe de Esquina", "rápido")],
      "FÁCIL"),
    E("Comboio do Porto", 2, "[[Porto Novo]] · [[Praia de Belas]]",
      "Encontro grande e coordenado — o Líder faz cinco valerem por oito.",
      [(3, "Escolta de Comboio", "rápido"), (4, "Estivador de Confiança", "lento"), (1, "Chefe de Armazém", "lento")],
      "DIFICIL"),
    E("Confusão no Boteco", 0, "Genérico — qualquer boteco depois da segunda rodada.",
      "Começa com um empurrão e termina com a rua inteira olhando. Ninguém puxa arma de fogo: é briga de bar.",
      [(6, "Arruaceiro", "lento"), (2, "Boêmio Armado", "rápido")],
      "DIFICIL"),
    E("Contenção em Petrópolis", 2, "[[Petrópolis]] · [[Rua das Indústrias]]",
      "Um muro que não morre, dois que prendem e um que pune quem se expõe.",
      [(2, "Exoesqueleto do BOPE", "lento"), (3, "Cabo de Choque", "lento"), (1, "Franco-Atirador da Brigada", "rápido")],
      "DIFICIL"),
    E("Correria do Camelódromo", 0, "[[Camelódromo]]",
      "Perseguição, não abate — quem parar pra brigar perde a carga.",
      [(1, "Mula do Cartel", "rápido"), (4, "Agulha de Beco", "rápido"), (2, "Catador Armado", "lento")],
      "DIFICIL"),
    E("Drones da Base", 1, "[[Base Fantasma]] · [[Zona Deserta]]",
      "Os hackers gritam no rádio e os drones obedecem a quem gritar mais alto.",
      [(6, "Drone Sequestrado", "rápido"), (3, "Drone de Guarda", "lento")],
      "DIFICIL"),
    E("Escritório dos Moinhos", 2, "[[Moinhos de Vento]] · [[Centro Histórico]]",
      "O andar corporativo reage: rotina nos capangas e um terno indo atrás de um só.",
      [(2, "Operador Trônico", "lento"), (4, "Segurança de Crachá", "lento"), (2, "Escolta de Diretoria", "super rápido")],
      "DIFICIL"),
    E("Estufa à Noite", 1, "[[Estufa Histórica]] · [[Jardim Botânico]]",
      "Dois furtam, um apaga a luz. Quando a luz volta, falta alguma coisa.",
      [(4, "Biopirata", "rápido"), (3, "Sabotador", "lento")],
      "FÁCIL"),
    E("Ferro-Velho da Zona", 1, "[[Zona Deserta]] · [[Depósito de Sucata]] · [[Restinga]]",
      "Mexer na pilha errada. A marreta vem junto com a prótese que ela construiu.",
      [(5, "Ferro-Velho", "lento"), (7, "Catador Armado", "rápido")],
      "DIFICIL"),
    E("Galpão de Teste", 2, "[[Instituto Técnico Tramontina]] · [[Petrópolis]]",
      "A máquina de teste não sabe que parou de ser exercício — e a portaria acha que é culpa do grupo.",
      [(2, "Protótipo de Exoesqueleto", "lento"), (4, "Segurança de Portaria", "lento")],
      "DIFICIL"),
    E("Guarita da Estrada", 0, "[[Passo D'Areia]] · [[Garagem dos Rachas]]",
      "O grupo mexe num carro que não é dele. A oficina inteira para.",
      [(4, "Segurança do Cartel dos Eixos", "lento"), (1, "Boêmio Armado", "rápido")],
      "FÁCIL"),
    E("Jantar nos Moinhos", 2, "[[Padre Chagas]] · [[Moinhos de Vento]]",
      "Combate social: começar a briga já custa. O Supressor tira um do grupo por três rodadas.",
      [(2, "Corretor de Chantagem", "lento"), (3, "Escolta Particular", "rápido"), (2, "Envenenador", "lento")],
      "LETAL"),
    E("Mercado do Velho", 2, "[[Mercado Público]] · [[Centro Histórico]] · [[Palafitas do Mercado]]",
      "O velho recebe sentado e não levanta. Quem levanta é a mesa inteira em volta dele.",
      [(1, "Velho da Família", "lento"), (4, "Leão de Chácara", "lento"), (2, "Cobrador de Ponto", "lento"), (2, "Agulha de Beco", "rápido")],
      "FÁCIL"),
    E("Milícia na Fronteira", 2, "[[Costa e Silva]] · [[Zona Deserta]]",
      "O que sobrou da tropa, sem regulamento, na linha onde a cidade acaba.",
      [(4, "Miliciano Veterano", "lento"), (4, "Ex-Praça", "lento")],
      "DIFICIL"),
    E("Modelo em Campo", 3, "[[Zona Deserta]] · [[Costa e Silva]]",
      "A encomenda do regime saiu do galpão pra um teste de campo. O campo é onde o grupo está.",
      [(1, "Modelo Militar", "lento"), (2, "Pelotão de Guarnição", "lento")],
      "LETAL"),
    E("Muro de Ipanema", 1, "[[Ipanema]] · [[Clube de Golfe de Ipanema]]",
      "A guarita barra, o rádio chama, e o chefe aparece quando já é tarde.",
      [(6, "Segurança de Condomínio", "lento"), (2, "Chefe de Segurança", "rápido")],
      "LETAL"),
    E("O Barão na Rota", 3, "[[Jardim Itu]] · [[Restinga]]",
      "O dono da rota veio ver a carga com os próprios olhos — e trouxe a escolta séria.",
      [(1, "Barão do Cartel", "super rápido"), (2, "Braço Armado do Cartel", "lento"), (1, "Químico de Campo", "lento")],
      "LETAL"),
    E("O Ninho", 3, "[[Delta Radioativo]] · [[Zona Deserta]]",
      "A estação abandonada inteira é o inimigo — e alguma coisa rápida demais circula entre as ruínas.",
      [(1, "Colônia Mutante", "lento"), (1, "Corredor Fantasma", "super rápido"), (4, "Rato-do-Delta", "rápido")],
      "LETAL"),
    E("O Sargento Cobra", 2, "Genérico — onde a Brigada souber que o grupo está.",
      "Brum cobra o que a Brigada finge não saber — e veio com turno inteiro atrás.",
      [(1, "Sargento Valdir Brum", "super rápido"), (1, "Guarda Oficial", "lento"), (4, "Cabo de Choque", "lento"), (4, "Brigadiano de Esquina", "lento")],
      "FÁCIL"),
    E("O Subsolo da Orion", 3, "[[Complexo de Testes Orion]] · [[Zona Deserta]]",
      "Clímax de campanha: o que fugiu e o que nunca saiu.",
      [(1, "Protótipo Orion", "lento"), (2, "Drone de Guarda", "rápido"), (1, "Androide de Vigilância", "lento")],
      "DIFICIL"),
    E("Operação Silêncio", 1, "[[Bom Fim]] · [[Centro Histórico]]",
      "Objetivo dividido: brigar e tirar gente de lá antes da Brigada fechar o quarteirão.",
      [(6, "Cabo de Choque", "lento"), (3, "Brigadiano Atirador", "rápido"), (4, "Cão de Brigada", "rápido")],
      "LETAL"),
    E("Pedágio da Estrada", 1, "[[Restinga]]",
      "Posição fixa com fogo de cobertura; a Artilharia trava o avanço.",
      [(4, "Miliciano da Estrada", "lento"), (2, "Guarita da Restinga", "lento"), (3, "Piloto de Racha", "rápido")],
      "DIFICIL"),
    E("Piquete na Indústria", 0, "[[Rua das Indústrias]] · [[Petrópolis]] · [[Nova Sarandi]]",
      "Greve fechando a rua. Passar é escolher lado — e nenhum lado esquece.",
      [(7, "Piquete", "lento"), (1, "Chefe de Esquina", "rápido")],
      "DIFICIL"),
    E("Porta do Teatro", 2, "[[Teatro Quarto Distrito]]",
      "Dois muros na frente e uma agulha que já está atrás.",
      [(4, "Leão de Chácara", "lento"), (2, "Agulha da Ordem", "super rápido")],
      "FÁCIL"),
    E("Pátio da Tramontina", 1, "[[Portaria da Tramontina]] · [[Petrópolis]] · [[Nova Sarandi]]",
      "Turno da madrugada no pátio da fábrica. Faca com número de série dos dois lados.",
      [(5, "Segurança de Portaria", "lento"), (3, "Capanga de Oficina", "rápido")],
      "DIFICIL"),
    E("Ratos na Rua do Rato", 0, "[[Delta Radioativo]] · [[Rua do Rato]]",
      "Atravessar a pé, de noite, com cheiro de sangue. Número cansa.",
      [(10, "Rato-do-Delta", "rápido")],
      "LETAL"),
    E("Refino Grande", 2, "[[Jardim Itu]] · [[Fábrica Itú Química]]",
      "Carga grande saindo. A química cai de área e a escolta não conversa.",
      [(2, "Químico de Campo", "lento"), (2, "Braço Armado do Cartel", "lento"), (4, "Guarda de Refino", "lento")],
      "LETAL"),
    E("Refino do Itu", 1, "[[Fábrica Itú Química]] · [[Jardim Itu]]",
      "Cenário que machuca (vapor, frasco, fogo) e um terceiro lado que não é amigo.",
      [(4, "Guarda de Refino", "lento"), (2, "Refinador", "lento"), (2, "Fiscal de Patente", "rápido")],
      "DIFICIL"),
    E("Ronda da Portaria", 1, "[[Moinhos de Vento]] · [[Ipanema]] · [[Escola Técnica Gradiente]]",
      "Entrar sem crachá. O drone vê antes do porteiro — derrubar o drone é a primeira decisão.",
      [(4, "Segurança de Crachá", "lento"), (3, "Drone de Vigilância", "rápido")],
      "FÁCIL"),
    E("Saída do Gre-Nal", 0, "[[Estádio Beira-Rio]] · [[Estádio Olímpico Monumental]]",
      "Dia de jogo. Derrubar o cabeça dispersa o bando.",
      [(7, "Representante da Camisa 12", "lento"), (2, "Cabeça de Torcida", "rápido")],
      "LETAL"),
    E("Sucata Fechada", 2, "[[Zona Deserta]] · [[Oficina de Sucata]] · [[Restinga]]",
      "O dono do ferro negocia primeiro. Quando para de negociar, já cercou.",
      [(2, "Mestre de Sucata", "lento"), (5, "Ferro-Velho", "lento"), (6, "Catador Armado", "rápido")],
      "DIFICIL"),
    E("Tocaia Flutuante", 1, "[[Cidade Baixa]]",
      "Três lados, chão instável, ninguém é aliado.",
      [(4, "Cabo de Choque", "lento"), (2, "Piloto de Anfíbio", "rápido"), (3, "Atirador de Palafita", "lento")],
      "DIFICIL"),
    E("Travessia do Barqueiro", 0, "[[Lago Guaíba]] · [[Cidade Baixa]]",
      "O barqueiro cobra na metade do caminho. Brigar em cima d'água é o problema dele, não teu.",
      [(5, "Barqueiro Armado", "rápido"), (3, "Mula do Cartel", "rápido")],
      "DIFICIL"),
    E("Trilho da Sarandi", 1, "[[Ferroviária Nacional]] · [[Nova Sarandi]]",
      "Tudo em cima de algo que anda; quem parar, fica pra trás.",
      [(7, "Saqueador de Vagão", "rápido"), (2, "Cabeça de Torcida", "lento")],
      "DIFICIL"),
    E("Bicharada da Restinga", 0, "[[Restinga]] · [[Zona Deserta]]",
      "O rebanho solto não foge: fecha o caminho e vem de cabeça baixa.",
      [(6, "Bode da Restinga", "rápido"), (1, "Carneiro do Morro", "lento")],
      "DIFICIL"),
    E("Cascavel no Vão", 1, "[[Quarto Distrito]] · [[Cidade Baixa]]",
      "Mexer na carga errada. O guizo vem de três lados do vão do cais ao mesmo tempo.",
      [(5, "Cascavel do Cais", "rápido"), (2, "Rato-do-Delta", "rápido")],
      "FÁCIL"),
    E("O Touro Solto", 2, "[[Zona Deserta]] · [[Costa e Silva]]",
      "Gado sem dono no meio da estrada — e nada convence dois mil quilos a sair.",
      [(2, "Touro do Pasto Morto", "lento"), (2, "Javali da Restinga", "rápido")],
      "DIFICIL"),
    E("A Onça do Jardim", 3, "[[Jardim Botânico]] · [[Petrópolis]]",
      "Alguma coisa come em cima do telhado e larga o resto na calçada. São duas.",
      [(2, "Onça do Jardim", "super rápido"), (4, "Capivara Blindada", "lento")],
      "DIFICIL"),
    E("O Fundo do Delta", 3, "[[Delta Radioativo]] · [[Lagoa do Pinheiro]]",
      "O fundo do Delta inteiro se mexe junto. Ela não persegue: o resto é que traz.",
      [(1, "A Mãe do Delta", "lento"), (2, "Jacaré do Arroio", "lento"), (4, "Cão Mutante", "rápido"), (6, "Rato-do-Delta", "rápido")],
      "LETAL"),
]
